force-app/main/default/objects/Case/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Solution__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sectors__c.field-meta.xml
<CustomField>
    <fullName>Sectors__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto &amp; Auto Components</fullName>
            </value>
            <value>
                <fullName>CIP &amp; Retail</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Global Delivery</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Law Firms</fullName>
            </value>
            <value>
                <fullName>Owners &amp; Private Clients</fullName>
            </value>
            <value>
                <fullName>PE/VC</fullName>
            </value>
            <value>
                <fullName>Pharma &amp; Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Real Estate &amp; Infra</fullName>
            </value>
            <value>
                <fullName>TMT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case Support</businessProcess>
    <label>Case</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Record_Type_For_Read_Only_cases.recordType-meta.xml
<RecordType>
    <fullName>Record_Type_For_Read_Only_cases</fullName>
    <active>true</active>
    <businessProcess>Support Process For Case Page Layout</businessProcess>
    <label>Record Type For Read Only cases</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <inlineHelpText>Source of the new client</inlineHelpText>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <description>This is having details of GT Expertise.</description>
    <label>Expertise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Solution__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Preliminary_New_Clients__c.field-meta.xml
<CustomField>
    <fullName>Preliminary_New_Clients__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Preliminary New Clients</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>New Clients</relationshipLabel>
    <relationshipName>New_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <description>This is having all the sector details of GT.</description>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <inlineHelpText>Choose an Integrated Solution or Bespoke Solution</inlineHelpText>
    <label>Solution</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sector__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SolutionValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Third Party</fullName>
    </customValue>
    <customValue>
        <fullName>Law Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Investor</fullName>
    </customValue>
    <customValue>
        <fullName>Campaign</fullName>
    </customValue>
    <customValue>
        <fullName>Word of Mouth</fullName>
    </customValue>
    <customValue>
        <fullName>Organic Search</fullName>
    </customValue>
    <customValue>
        <fullName>Twitter</fullName>
    </customValue>
    <customValue>
        <fullName>LinkedIn</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Thought Leadership Events</fullName>
        <label>Thought Leadership</label>
    </customValue>
    <customValue>
        <fullName>Other Events</fullName>
    </customValue>
    <customValue>
        <fullName>Past Relationship</fullName>
    </customValue>
    <customValue>
        <fullName>Webinar</fullName>
    </customValue>
    <customValue>
        <fullName>External Events</fullName>
    </customValue>
    <customValue>
        <fullName>GT Events</fullName>
    </customValue>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Publications</fullName>
    </customValue>
    <customValue>
        <fullName>Cross Sell</fullName>
        <label>Cross Sell / Up Sell Enquiries</label>
    </customValue>
    <customValue>
        <fullName>Existing Client</fullName>
    </customValue>
    <customValue>
        <fullName>GT Employee</fullName>
    </customValue>
    <customValue>
        <fullName>GT Member Firms</fullName>
    </customValue>
    <customValue>
        <fullName>Chamber</fullName>
        <label>Chambers</label>
    </customValue>
    <customValue>
        <fullName>Investors / Private Equity Firms</fullName>
    </customValue>
    <customValue>
        <fullName>Visiting card</fullName>
    </customValue>
    <customValue>
        <fullName>Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Corridors</fullName>
    </customValue>
    <description>It depicts the Lead Channel information, from where the Lead is coming.</description>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Auto &amp; Auto Components</fullName>
    </customValue>
    <customValue>
        <fullName>CIP &amp; Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>Global Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Law Firms</fullName>
    </customValue>
    <customValue>
        <fullName>Owners &amp; Private Clients</fullName>
    </customValue>
    <customValue>
        <fullName>PE/VC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma &amp; Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate &amp; Infra</fullName>
    </customValue>
    <customValue>
        <fullName>TMT</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Sector</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CaseTriggerHelper.cls
public without sharing class CaseTriggerHelper {
    public static void updateStatusOnCase(List<Case> caseList){
        try{
            for(Case caseObj:caseList){
                caseObj.Status = 'In Progress';
            }
        }
        catch(Exception e){
            System.debug('Error##'+e.getLineNumber());
        }
        
    }
    /*By :-Suresh gupta
	*Date:- 23 Feb 2023
	*Purpose:- Created New Client When Case Status is "Convert to New Client"
	*/
    /*------------------------------------------------------*/   
    
    public static void afterUpdateMethod(List<Case> caseList){
        try{
            List<Lead> leadListToBeInserted = New List<Lead>();
            
            Group sectorAssignmentTeamQueue= [SELECT Id from Group WHERE Type = 'Queue' AND DeveloperName = 'SectorAssignmentTeam'];
            Id readRecordTypeIdOfCase =Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Record_Type_For_Read_Only_cases').getRecordTypeId();
            List<Case> caseListToBeUpdated = new List<Case>();
            for(Case caseObj:caseList){
                system.debug('afterInsertMethod Method has been Called');
                if(String.isNotBlank(caseObj.Sectors__c) && 
                   String.isNotBlank(caseObj.SuppliedName) && 
                   String.isNotBlank(caseObj.SuppliedEmail) && 
                   String.isNotBlank(caseObj.Website__c) && 
                   String.isNotBlank(caseObj.Client_Name__c) && 
                   caseObj.SuppliedPhone != null){
                       system.debug('Inside Loop');
                       Lead leadObj = new Lead();
                       if(caseObj.Country_Code__c!=null){
                           leadObj.CountryCode__c = caseObj.Country_Code__c;
                       }
                       leadObj.LastName = caseObj.SuppliedName!=null?caseObj.SuppliedName:caseObj.CaseNumber;//case number
                       System.debug('check sector'+caseObj.Sectors__c);
                       leadObj.Sector__c= caseObj.Sectors__c;
                       leadObj.Status = 'Internal / External Discussions';
                       //leadObj.Expertise__c = caseObj.Expertise__c;
                       //leadObj.Solution__c = caseObj.Solution__c;
                       leadObj.LeadSource = 'Email';
                       leadObj.Channel__c = 'Digital';
                       leadObj.CountryCode__c = caseObj.Country_Code__c;
                       leadObj.MobilePhone = caseObj.SuppliedPhone !=null ? caseObj.SuppliedPhone : '';
                       leadObj.Email = caseObj.SuppliedEmail !=null ? caseObj.SuppliedEmail : 'noemail@test.com';
                       leadObj.Company = caseObj.Client_Name__c;//email to case//new client source
                       //leadObj.OwnerId = sectorAssignmentTeamQueue.id;
                       leadObj.Website = caseObj.Website__c;
                       leadObj.Preliminary_New_Clients__c = caseObj.id;
                       leadListToBeInserted.add(leadObj);
                       //updating record type of Preliminary New Client
                   }
            }
            if(leadListToBeInserted.size()>0){
                insert leadListToBeInserted;
                
                system.debug('New Clients Created Successfully');
                
            }
            if(caseList.size()>0){
                
                for(Case caseObj:[select id,RecordTypeId from Case where id IN:caseList]){
                    caseObj.RecordTypeId = readRecordTypeIdOfCase;
                    caseListToBeUpdated.add(caseObj);
                }


                //update caseListToBeUpdated;
                system.debug('Case Updated Successfully');
            }
        }
        catch(exception e){
            system.debug('Exception---.'+e.getMessage());
            system.debug('Exception---.'+e.getLineNumber());
        }
        
    }
}