force-app/main/default/objects/Case/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Solution__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sectors__c.field-meta.xml
<CustomField>
    <fullName>Sectors__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto &amp; Auto Components</fullName>
            </value>
            <value>
                <fullName>CIP &amp; Retail</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Global Delivery</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Law Firms</fullName>
            </value>
            <value>
                <fullName>Owners &amp; Private Clients</fullName>
            </value>
            <value>
                <fullName>PE/VC</fullName>
            </value>
            <value>
                <fullName>Pharma &amp; Healthcare Services</fullName>
            </value>
            <value>
                <fullName>Real Estate &amp; Infra</fullName>
            </value>
            <value>
                <fullName>TMT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Sector__c.field-meta.xml
<CustomField>
    <fullName>Sub_Sector__c</fullName>
    <label>Sub Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case Support</businessProcess>
    <label>Case</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <inlineHelpText>Source of the new client</inlineHelpText>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <description>This is having details of GT Expertise.</description>
    <label>Expertise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Solution__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Preliminary_New_Clients__c.field-meta.xml
<CustomField>
    <fullName>Preliminary_New_Clients__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Preliminary New Clients</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>New Clients</relationshipLabel>
    <relationshipName>New_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <description>This is having all the sector details of GT.</description>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <inlineHelpText>Choose an Integrated Solution or Bespoke Solution</inlineHelpText>
    <label>Solution</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sector__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SolutionValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SubSector__c.field-meta.xml
<CustomField>
    <fullName>SubSector__c</fullName>
    <description>It contains the information of sub sector related to particular sector.</description>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sector__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SubSector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Third Party</fullName>
    </customValue>
    <customValue>
        <fullName>Law Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Investor</fullName>
    </customValue>
    <customValue>
        <fullName>Campaign</fullName>
    </customValue>
    <customValue>
        <fullName>Word of Mouth</fullName>
    </customValue>
    <customValue>
        <fullName>Organic Search</fullName>
    </customValue>
    <customValue>
        <fullName>Twitter</fullName>
    </customValue>
    <customValue>
        <fullName>LinkedIn</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Thought Leadership Events</fullName>
        <label>Thought Leadership</label>
    </customValue>
    <customValue>
        <fullName>Other Events</fullName>
    </customValue>
    <customValue>
        <fullName>Past Relationship</fullName>
    </customValue>
    <customValue>
        <fullName>Webinar</fullName>
    </customValue>
    <customValue>
        <fullName>External Events</fullName>
    </customValue>
    <customValue>
        <fullName>GT Events</fullName>
    </customValue>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Publications</fullName>
    </customValue>
    <customValue>
        <fullName>Cross Sell</fullName>
        <label>Cross Sell / Up Sell Enquiries</label>
    </customValue>
    <customValue>
        <fullName>Existing Client</fullName>
    </customValue>
    <customValue>
        <fullName>GT Employee</fullName>
    </customValue>
    <customValue>
        <fullName>GT Member Firms</fullName>
    </customValue>
    <customValue>
        <fullName>Chamber</fullName>
        <label>Chambers</label>
    </customValue>
    <customValue>
        <fullName>Investors / Private Equity Firms</fullName>
    </customValue>
    <customValue>
        <fullName>Visiting card</fullName>
    </customValue>
    <customValue>
        <fullName>Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Corridors</fullName>
    </customValue>
    <description>It depicts the Lead Channel information, from where the Lead is coming.</description>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Auto &amp; Auto Components</fullName>
    </customValue>
    <customValue>
        <fullName>CIP &amp; Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>Global Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Law Firms</fullName>
    </customValue>
    <customValue>
        <fullName>Owners &amp; Private Clients</fullName>
    </customValue>
    <customValue>
        <fullName>PE/VC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma &amp; Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate &amp; Infra</fullName>
    </customValue>
    <customValue>
        <fullName>TMT</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Sector</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SubSector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Auto &amp; Auto Components</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospace &amp; defense</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer, Retail and E-commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Food &amp; Agri</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial products</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>PE / VC</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate &amp; Infra</fullName>
    </customValue>
    <customValue>
        <fullName>Cleantech</fullName>
    </customValue>
    <customValue>
        <fullName>Energy &amp; natural resources</fullName>
    </customValue>
    <customValue>
        <fullName>Technology</fullName>
    </customValue>
    <customValue>
        <fullName>Media &amp; telecom</fullName>
        <label>Media &amp; Telecom</label>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmaceuticals</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Global Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Owners &amp; Private Clients</fullName>
    </customValue>
    <customValue>
        <fullName>New Industry</fullName>
    </customValue>
    <customValue>
        <fullName>E-commerce</fullName>
        <isActive>false</isActive>
        <label>E-commerce</label>
    </customValue>
    <customValue>
        <fullName>Fast Moving Consumer Goods (FMCG)</fullName>
        <isActive>false</isActive>
        <label>Fast Moving Consumer Goods (FMCG)</label>
    </customValue>
    <customValue>
        <fullName>Transform</fullName>
        <isActive>false</isActive>
        <label>Transform</label>
    </customValue>
    <customValue>
        <fullName>Enhance</fullName>
        <isActive>false</isActive>
        <label>Enhance</label>
    </customValue>
    <customValue>
        <fullName>Grow</fullName>
        <isActive>false</isActive>
        <label>Grow</label>
    </customValue>
    <customValue>
        <fullName>Agri-business</fullName>
        <isActive>false</isActive>
        <label>Agri-business</label>
    </customValue>
    <customValue>
        <fullName>Consumer durables</fullName>
        <isActive>false</isActive>
        <label>Consumer durables</label>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
        <isActive>false</isActive>
        <label>Retail</label>
    </customValue>
    <description>It contains the information of sub sector related to particular sector</description>
    <masterLabel>Sub Sector</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EmailtoCaseAuraController.cls
public without sharing class EmailtoCaseAuraController {
    @AuraEnabled
    public static Boolean createNewClient(String recordId){
        Boolean returnValue;
        System.debug('Inside Method');
        try {
            Case caseObj=[select id,CaseNumber,SuppliedName,Subject,Sectors__c,Sub_Sector__c,SuppliedEmail,Status,Client_Name__c,
                          Owner.Name,Lead_Created__c,Solution__c,Expertise__c,SuppliedPhone, Remarks__c, Website__c from Case
                          where id =: recordId];
            Group queue= [SELECT Id from Group WHERE Type = 'Queue' AND DeveloperName = 'SectorAssignmentTeam'];
            //List<Case> updateCaseList = new List<Case>();
            //List<Lead> updateLeadList = new List<Lead>();
            System.debug('Queue Name'+queue.id);
            if(caseObj != Null){
                System.debug('Case is not Empty' + caseObj);
                if(String.isNotBlank(caseObj.Sectors__c) && String.isNotBlank(caseObj.SuppliedName) && String.isNotBlank(caseObj.SuppliedEmail)
                   && String.isNotBlank(caseObj.Website__c) && String.isNotBlank(caseObj.Client_Name__c) && caseObj.SuppliedPhone != null){
                       System.debug('Inside if');
                       String str=caseObj.SuppliedEmail;
                       String splitString = str.substringAfter('@');
                       String companyEmail = splitString.substringBefore('.');
                       caseObj.Lead_Created__c = true;
                       caseObj.Status = 'Converted to New Client';
                       Lead leadObj = new Lead();
                       leadObj.LastName = caseObj.SuppliedName!=null?caseObj.SuppliedName:caseObj.CaseNumber;//case number
                       leadObj.Status = 'New';
                       System.debug('check sector'+caseObj.Sectors__c);
                       leadObj.Sector__c= caseObj.Sectors__c;
                       //leadObj.SubSector__c= caseObj.Sub_Sector__c; 
                       leadObj.Expertise__c = caseObj.Expertise__c;
                       leadObj.Solution__c = caseObj.Solution__c;
                       leadObj.LeadSource = 'Email';
                       leadObj.Channel__c = 'Digital';
                       leadObj.MobilePhone = caseObj.SuppliedPhone !=null ? caseObj.SuppliedPhone : '';
                       leadObj.Preliminary_New_Clients__c = caseObj.id;
                       leadObj.Email = caseObj.SuppliedEmail !=null ? caseObj.SuppliedEmail : 'noemail@test.com';
                       leadObj.Company = caseObj.Client_Name__c;//email to case//new client source
                       try{
                           update caseObj;
                           insert leadObj;
                           System.debug('lead created : ' + leadObj.Id);
                           returnValue = true;
                       }
                       catch(Exception e){
                           System.debug('Error'+e.getLineNumber() + ' and message : ' + e.getMessage());
                           returnValue = false;
                       }
                   }
                
                else{
                    returnValue = false;
                        /*System.debug('Inside else');
                        String str=caseObj.SuppliedEmail;
                        String splitString = str.substringAfter('@');
                        String companyEmail = splitString.substringBefore('.');
                        caseObj.Lead_Created__c = true;
                        Lead leadObj = new Lead();
                        leadObj.LastName = caseObj.SuppliedName!=null?caseObj.SuppliedName:caseObj.CaseNumber;//case number
                        leadObj.Status = 'New';
                        System.debug('above owner id');
                        leadObj.OwnerId = queue.id;
                        System.debug('below Email');
                        leadObj.LeadSource = 'Email';
                        leadObj.Channel__c = 'Digital';
                        leadObj.Preliminary_New_Clients__c = caseObj.id;
                        leadObj.MobilePhone = caseObj.SuppliedPhone!=null?caseObj.SuppliedPhone:'';
                        leadObj.Email = caseObj.SuppliedEmail!=null?caseObj.SuppliedEmail:'noemail@test.com';
                        leadObj.Company = caseObj.Client_Name__c;//email to case//new client source
                        //updateLeadList.add(leadObj);
                        //updateCaseList.add(caseObj);*/
                }
            }
            
            System.debug('returnValue : ' + returnValue);
            return returnValue;            
        } 
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
            
        }
    }
}