force-app/main/default/objects/FileRelatedInformation__c/FileRelatedInformation__c.object-meta.xml
<CustomObject>
    <label>File Related Information</label>
    <nameField>
        <label>File Related Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>File Related Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FileRelatedInformation__c/fields/EnquiryStage__c.field-meta.xml
<CustomField>
    <fullName>EnquiryStage__c</fullName>
    <label>Enquiry Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FileRelatedInformation__c/fields/FileURL__c.field-meta.xml
<CustomField>
    <fullName>FileURL__c</fullName>
    <label>File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/FileRelatedInformation__c/fields/ParentName__c.field-meta.xml
<CustomField>
    <fullName>ParentName__c</fullName>
    <label>Parent Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FileRelatedInformation__c/fields/RelatedClient__c.field-meta.xml
<CustomField>
    <fullName>RelatedClient__c</fullName>
    <label>Related Client</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <label>Enquiry</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContentDocumentLinkTriggerHandler.cls
public class ContentDocumentLinkTriggerHandler {
    //-------------------------Method for updating after insert context-------------------------------------------------------
    public static void isAfterInsert(List<ContentDocumentLink> ContentDocumentLinkList) {
        insertFileRelatedInformationInACustomObject(ContentDocumentLinkList); 
    }
    
     //-------------------------Inserting file related information in a custom object-------------------------------------------
    public static void insertFileRelatedInformationInACustomObject(List<ContentDocumentLink> ContentDocumentLinkList) {
        try{ 
            List<FileRelatedInformation__c> cusFilObjList = new List<FileRelatedInformation__c>();
            Set<Id> linkEntitId = new Set<Id>();
            Set<Id> contDocId = new Set<Id>();
            List<Opportunity> oppObjList = new List<Opportunity>();
            
            for(ContentDocumentLink cntDocLink : ContentDocumentLinkList){
                if(String.isNotBlank(cntDocLink.LinkedEntityId) && String.isNotBlank(cntDocLink.ContentDocumentId)){
                    linkEntitId.add(cntDocLink.LinkedEntityId);
                    contDocId.add(cntDocLink.ContentDocumentId);
                    System.debug('contDocId : '+contDocId);
                }
            }
            List<User> userList = [Select Id From User Where Id =: linkEntitId];
            System.debug('userList=='+userList); 
            String idObj = '';
            String accName = '';
            if(linkEntitId.size() > 0){
                List<ContentDocumentLink> cntDocLinkList = [SELECT ContentDocument.Title, LinkedEntity.Name, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =:linkEntitId AND ContentDocumentId =:contDocId AND LinkedEntityId Not In: userList];
                System.debug('cntDcLinkList : '+cntDocLinkList);
                
                System.debug('linkEntitId : '+linkEntitId);
                List<Contact> cntList = [SELECT AccountId FROM Contact WHERE Id =:linkEntitId];
                System.debug('cntList : '+cntList);
                
                if(cntList.isEmpty()) {
                    oppObjList = [SELECT Id,AccountId,StageName,Expertise__c FROM Opportunity WHERE Id =:linkEntitId];
                    System.debug('oppObjList : '+oppObjList); 
                }
                
                if(cntList.size()>0){
                    idObj = cntList[0].AccountId;
                    System.debug('idObj Contact : '+idObj);
                } else if(oppObjList.size()>0){
                    idObj = oppObjList[0].AccountId;
                    System.debug('idObj Contact : '+idObj);
                }
                else{
                    idObj = '';
                }
                Account acc = [SELECT Id, Name FROM Account WHERE Id =:idObj];
                accName = acc.Name;
                System.debug('accName : '+accName);
                
                
                List<Job__c> Jobs = [SELECT Name FROM Job__c WHERE Enquiry__c =: oppObjList[0].Id]; 
                
                
                for(ContentDocumentLink cntDocLink: cntDocLinkList){
                    FileRelatedInformation__c cusFilObj = new FileRelatedInformation__c();
                    cusFilObj.Name = cntDocLink.ContentDocument.Title;
                    System.debug('cusFilObj.Name=='+cusFilObj.Name);
                    cusFilObj.RelatedClient__c = accName;
                    System.debug('cusFilObj.RelatedClient__c=='+cusFilObj.RelatedClient__c);
                    cusFilObj.EnquiryStage__c = oppObjList[0].StageName;
                    System.debug('cusFilObj.EnquiryStage__c=='+cusFilObj.EnquiryStage__c);
                    cusFilObj.Expertise__c = oppObjList[0].Expertise__c;
                    System.debug('cusFilObj.Expertise__c=='+cusFilObj.Expertise__c);
                    if(!Jobs.isEmpty()){
                        cusFilObj.Name = Jobs[0].Name ;
                        System.debug('cusFilObj.Name=='+cusFilObj.Name);
                    }
                    
                    cusFilObj.ParentName__c = cntDocLink.LinkedEntity.Name;
                    System.debug('cusFilObj.ParentName__c=='+cusFilObj.ParentName__c);
                    cusFilObj.FileURL__c = 'https://grantthornton--dev1.sandbox.lightning.force.com/lightning/r/ContentDocumentt/'+cntDocLink.ContentDocumentId+'/view';
                    cusFilObjList.add(cusFilObj);
                }
                
                if(!cusFilObjList.isEmpty()){
                    System.debug('cusFilObjList : '+cusFilObjList);
                    insert cusFilObjList;
                }
            }
        }
        catch(Exception e) {
            System.debug(e);
        }

    }

}