force-app/main/default/objects/Client_News__c/Client_News__c.object-meta.xml
<CustomObject>
    <label>Client News</label>
    <nameField>
        <label>Client News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_News__c/fields/New_Client__c.field-meta.xml
<CustomField>
    <fullName>New_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Client</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Client News</relationshipLabel>
    <relationshipName>Client_Newss</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/KeyDevAndAlertsControllerTest.cls
@isTest
private class KeyDevAndAlertsControllerTest{

	@testSetup static void setup(){
		
		Lead lead = new lead();
		lead.lastName = 'Test new client last name';
        lead.Company = 'Tata Steel Limited';
		lead.capIQId__c = 'IQ874170';
		insert lead;

		Client_News__c clientNewsObj = new Client_News__c();
		clientNewsObj.New_Client__c = lead.Id;
		clientNewsObj.Name = 'Test news';
		clientNewsObj.IQ_KEY_DEV_HEADLINE__c = 'Test headline';
		insert clientNewsObj;

		
	}

	@isTest static void testMethod1() {
		// code_block
		List<Lead> newClientList = [SELECT Id, Name, capIQId__c, (SELECT Id, Name, IQ_KEY_DEV_HEADLINE__c FROM Client_Newss__r ) FROM Lead];
		KeyDevAndAlertsController.getNewClient(newClientList[0].Id, 'Lead');	
	}

	@isTest static void testMethod2() {
		// code_block	
	}
}