force-app/main/default/objects/IntegratedEnquiry__c/IntegratedEnquiry__c.object-meta.xml
<CustomObject>
    <label>Integrated Enquiry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integrated Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IntegratedEnquiry__c/fields/CCApprovalRejectionRecommendation__c.field-meta.xml
<CustomField>
    <fullName>CCApprovalRejectionRecommendation__c</fullName>
    <label>CC_Approval / Rejection Recommendation</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/CCApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>CCApprovalStatus__c</fullName>
    <label>CC_Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/ClientBackground__c.field-meta.xml
<CustomField>
    <fullName>ClientBackground__c</fullName>
    <label>Client Background</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Solution1__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/GrowthPotential__c.field-meta.xml
<CustomField>
    <fullName>GrowthPotential__c</fullName>
    <label>Growth Potential</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/HowDidYouArriveAThisTentativeFee__c.field-meta.xml
<CustomField>
    <fullName>HowDidYouArriveAThisTentativeFee__c</fullName>
    <label>How did you arrive at this tentative fee</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/NSL__c.field-meta.xml
<CustomField>
    <fullName>NSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Integrated_Enquiries7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/NSLApprovalRejectionRecommendation__c.field-meta.xml
<CustomField>
    <fullName>NSLApprovalRejectionRecommendation__c</fullName>
    <label>NSL Approval / Rejection Recommendation</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/NSLApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>NSLApprovalStatus__c</fullName>
    <label>NSL Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/ShortSummary__c.field-meta.xml
<CustomField>
    <fullName>ShortSummary__c</fullName>
    <label>Short Summary</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <label>Solution not in use</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Solution</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/SubExpertise__c.field-meta.xml
<CustomField>
    <fullName>SubExpertise__c</fullName>
    <label>Sub Expertise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SubExpertise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/TentativeFee__c.field-meta.xml
<CustomField>
    <fullName>TentativeFee__c</fullName>
    <label>Tentative Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CCApprovalRejectionRecommendation__c.field-meta.xml
<CustomField>
    <fullName>CCApprovalRejectionRecommendation__c</fullName>
    <description>It depicts the Approval / Rejection recommendation status.</description>
    <inlineHelpText>Client Council Recommendations</inlineHelpText>
    <label>CC_Approval / Rejection Recommendation</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ClientBackground__c.field-meta.xml
<CustomField>
    <fullName>ClientBackground__c</fullName>
    <description>It depicts Client Background.</description>
    <inlineHelpText>Highest level parent within a corporate family tree that is domiciled in the same country</inlineHelpText>
    <label>Client Background</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <description>This is having details of GT Expertise.</description>
    <label>Expertise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Solution__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/HowDidYouArriveAThisTentativeFee__c.field-meta.xml
<CustomField>
    <fullName>HowDidYouArriveAThisTentativeFee__c</fullName>
    <label>How did you arrive at this tentative fee</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/NSL__c.field-meta.xml
<CustomField>
    <fullName>NSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It depicts which user has referred this lead.</description>
    <label>NSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/NSLApprovalRejectionRecommendation__c.field-meta.xml
<CustomField>
    <fullName>NSLApprovalRejectionRecommendation__c</fullName>
    <label>NSL Approval / Rejection Recommendation</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/NSLApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>NSLApprovalStatus__c</fullName>
    <label>NSL Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <description>This is having all the sector details of GT.</description>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ShortSummary__c.field-meta.xml
<CustomField>
    <fullName>ShortSummary__c</fullName>
    <inlineHelpText>Provide a short summary about the professional services required, or any additional remarks regarding the client</inlineHelpText>
    <label>Summary (Challenges, Opportunities etc)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <inlineHelpText>Choose an Integrated Solution or Bespoke Solution</inlineHelpText>
    <label>Solution</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sector__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SolutionValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SubExpertise__c.field-meta.xml
<CustomField>
    <fullName>SubExpertise__c</fullName>
    <description>It contains the information of sub expertise related to particular expertise.</description>
    <label>SMEG</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SubExpertise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/TentativeFee__c.field-meta.xml
<CustomField>
    <fullName>TentativeFee__c</fullName>
    <inlineHelpText>Information regarding new client from GT Website</inlineHelpText>
    <label>Tentative Fee</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CCApprovalRejectionRecommendation__c.field-meta.xml
<CustomField>
    <fullName>CCApprovalRejectionRecommendation__c</fullName>
    <label>CC_Approval / Rejection Recommendation</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CCApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>CCApprovalStatus__c</fullName>
    <label>CC_Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ClientBackground__c.field-meta.xml
<CustomField>
    <fullName>ClientBackground__c</fullName>
    <label>Client Background</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GrowthPotential__c.field-meta.xml
<CustomField>
    <fullName>GrowthPotential__c</fullName>
    <label>Growth Potential</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IntegratedEnquiry__c.field-meta.xml
<CustomField>
    <fullName>IntegratedEnquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Integrated Enquiry</label>
    <referenceTo>IntegratedEnquiry__c</referenceTo>
    <relationshipLabel>Enquiries (Integrated Enquiry)</relationshipLabel>
    <relationshipName>Enquiries1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSL__c.field-meta.xml
<CustomField>
    <fullName>NSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OpportunitiesnN4X</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSLApprovalRejectionRecommendation__c.field-meta.xml
<CustomField>
    <fullName>NSLApprovalRejectionRecommendation__c</fullName>
    <label>NSL Approval / Rejection Recommendation</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSLApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>NSLApprovalStatus__c</fullName>
    <label>NSLApprovalStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ShortSummary__c.field-meta.xml
<CustomField>
    <fullName>ShortSummary__c</fullName>
    <label>Short Summary</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <label>Solution</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SubExpertise__c.field-meta.xml
<CustomField>
    <fullName>SubExpertise__c</fullName>
    <label>Sub Expertise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SubExpertise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TentativeFee__c.field-meta.xml
<CustomField>
    <fullName>TentativeFee__c</fullName>
    <label>Initial Tentative Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Auto &amp; Auto Components</fullName>
    </customValue>
    <customValue>
        <fullName>CIP &amp; Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>Global Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Law Firms</fullName>
    </customValue>
    <customValue>
        <fullName>Owners &amp; Private Clients</fullName>
    </customValue>
    <customValue>
        <fullName>PE/VC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma &amp; Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate &amp; Infra</fullName>
    </customValue>
    <customValue>
        <fullName>TMT</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Sector</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SubExpertise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Attest Services</fullName>
    </customValue>
    <customValue>
        <fullName>BFSI Tax</fullName>
    </customValue>
    <customValue>
        <fullName>Business Intelligence and Information Management (BIIM)</fullName>
    </customValue>
    <customValue>
        <fullName>Compliance &amp; Outsourcing</fullName>
    </customValue>
    <customValue>
        <fullName>Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Intelligence</fullName>
    </customValue>
    <customValue>
        <fullName>Customer, marketing and sales</fullName>
    </customValue>
    <customValue>
        <fullName>CYBER</fullName>
    </customValue>
    <customValue>
        <fullName>DGTL</fullName>
    </customValue>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Digital CoE</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Tax</fullName>
    </customValue>
    <customValue>
        <fullName>Due Diligence</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Transformation and Optimisation</fullName>
    </customValue>
    <customValue>
        <fullName>ESG</fullName>
    </customValue>
    <customValue>
        <fullName>Forensic</fullName>
    </customValue>
    <customValue>
        <fullName>FRAS</fullName>
    </customValue>
    <customValue>
        <fullName>FS Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>FS Risk</fullName>
    </customValue>
    <customValue>
        <fullName>GD AUS</fullName>
    </customValue>
    <customValue>
        <fullName>GDUK</fullName>
    </customValue>
    <customValue>
        <fullName>GDUSA</fullName>
    </customValue>
    <customValue>
        <fullName>Global Audit Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Global Mobility Services</fullName>
    </customValue>
    <customValue>
        <fullName>Global Tax Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Governance Risk &amp; Operations (GRO)</fullName>
    </customValue>
    <customValue>
        <fullName>GRC</fullName>
    </customValue>
    <customValue>
        <fullName>GT International</fullName>
    </customValue>
    <customValue>
        <fullName>GTUSA</fullName>
    </customValue>
    <description>It contains the information of sub expertise related to particular expertise</description>
    <masterLabel>Sub Expertise</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AutoConvertLeadsTest.cls
/*
*Author :Gaurav Kumar 
*Description : AutoConvertLeads 
*Date :13/12/2022 
* 
*/
@isTest
public class AutoConvertLeadsTest {
    @isTest
    public static void leadAssignTest(){
        List<Id> leadIdList = new List<Id>();
        Profile pro = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        User u = new user();
        u.LastName = 'Testclassra Code';
        u.Email = 'test@test.com';
        u.Alias = 'Tcode';
        u.Username = 'testclasshhhy@test.com';
        u.CommunityNickname = 'test12';
        u.LocaleSidKey = 'en_US';
        u.TimeZoneSidKey = 'GMT';
        u.ProfileId = pro.Id;
        u.LanguageLocaleKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        insert u;
        
       /* 
        
        IntegratedEnquiry__c intEnqObj = new IntegratedEnquiry__c();
        intEnqObj.Company__c = 'Cloud Analogy';
        intEnqObj.Solution__c = 'ESOP';
        intEnqObj.Expertise__c = 'Human Capital Consulting';
        insert intEnqObj;
        
        Opportunity oppObj = new Opportunity();
        oppObj.IntegratedEnquiry__c = intEnqObj.Id;
        oppObj.AccountId = acc.Id;
        oppObj.Name = 'Test';
        oppObj.CloseDate = System.today();
        oppObj.StageName = 'New';
        insert oppObj;*/
        
        Lead obj1 = new Lead();
        obj1.LastName = 'Test Test';
        obj1.NSLApprovalStatus__c = 'Approved';
        obj1.Status = 'Accept Client';
        obj1.CCApprovalStatus__c = 'Approved';
        obj1.OnNewStage__c = 2323;
        obj1.Expertise__c = 'Human Capital Consulting';
        obj1.Solution__c = 'ESOP';
        obj1.SubExpertise__c = 'Cyber';
        obj1.Region__c = 'North';
        obj1.NSLApprovalRejectionRecommendation__c = 'fgnc';
        obj1.Company = 'Cloud Analogy';
        obj1.NSL__c = u.Id;
        obj1.OwnerId = u.Id;
        obj1.CCApprovalRejectionRecommendation__c= 'sdfsdf';
        obj1.ClientBackground__c = 'sdasd';
        obj1.GrowthPotential__c = 'fdsdf';
        obj1.TentativeFee__c =123;
        obj1.HowDidYouArriveAThisTentativeFee__c = 'dasd';
        obj1.ShortSummary__c = 'sdfsad';
        //obj1.CreatedDate = datetime.newInstance('2022', '12', '13');
        obj1.Sector__c = 'Automobile & Auto Components';
        obj1.Email = 'test@gmail.com';
        obj1.IsLead__c = True;
        obj1.MobilePhone = '1234567891';
        insert obj1;
        leadIdList.add(obj1.Id);
        
        Test.startTest();
        AutoConvertLeads.leadAssign(leadIdList);
        Test.stopTest();
        
        
        IntegratedEnquiry__c intEnqObj = new IntegratedEnquiry__c();
        intEnqObj.Company__c = 'Cloud Analogy';
        intEnqObj.Solution1__c = 'ESOP';
        intEnqObj.Expertise__c = 'Human Capital Consulting';
        insert intEnqObj;
        
        /*try{
            Test.startTest();
            AutoConvertLeads.leadAssign(leadIdList);
            Test.stopTest();
        }
        Catch(Exception ex){
            System.debug('Error :'+ex.getMessage());
            System.debug('In Line Number :'+ex.getLineNumber());
        }*/
    }
}