force-app/main/default/objects/IntegratedEnquiry__c/IntegratedEnquiry__c.object-meta.xml
<CustomObject>
    <label>Integrated Enquiry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integrated Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IntegratedEnquiry__c/fields/ExpertiesForDuplicateRule__c.field-meta.xml
<CustomField>
    <fullName>ExpertiesForDuplicateRule__c</fullName>
    <label>ExpertiesForDuplicateRule</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Solution1__c.field-meta.xml
<CustomField>
    <fullName>Solution1__c</fullName>
    <label>Solution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SolutionValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/SubexpertiesForDuplicateRule__c.field-meta.xml
<CustomField>
    <fullName>SubexpertiesForDuplicateRule__c</fullName>
    <label>SubexpertiesForDuplicateRule</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/checkDupliacteForIntegratedEnquiry.cls
public class checkDupliacteForIntegratedEnquiry {
    @AuraEnabled(cacheable=true)
    public static Boolean checkDuplicate(string experty,string subexperty, string Company,string solution) {
        boolean isIntegratedEnquiryDuplicate=false;
        try{
        List<integratedEnquiry__c> listIntegratedEnq=[Select id,SubexpertiesForDuplicateRule__c ,ExpertiesForDuplicateRule__c,Solution1__c,Company__c from IntegratedEnquiry__c];
        for(integratedEnquiry__c integratedEnq : listIntegratedEnq){
            if(integratedEnq.SubexpertiesForDuplicateRule__c==subexperty && integratedEnq.ExpertiesForDuplicateRule__c==experty && integratedEnq.Solution1__c==solution && integratedEnq.Company__c==Company ){
                if(!isIntegratedEnquiryDuplicate){
                    isIntegratedEnquiryDuplicate=true;
                }
            }
        }

      }catch(Exception e){
        
      }
     
     return isIntegratedEnquiryDuplicate;
    }
}