force-app/main/default/objects/IntegratedEnquiry__c/IntegratedEnquiry__c.object-meta.xml
<CustomObject>
    <label>Integrated Enquiry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integrated Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Creative_Hub_Id__c.field-meta.xml
<CustomField>
    <fullName>Creative_Hub_Id__c</fullName>
    <label>Creative Hub Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Creative_Hub_Status__c.field-meta.xml
<CustomField>
    <fullName>Creative_Hub_Status__c</fullName>
    <label>Creative Hub Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Pitch_Presentation_Status__c.field-meta.xml
<CustomField>
    <fullName>Pitch_Presentation_Status__c</fullName>
    <label>Pitch Presentation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Creative_Hub_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Proposal_Status__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Status__c</fullName>
    <label>Proposal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Creative_Hub_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Creative_Hub_Id__c.field-meta.xml
<CustomField>
    <fullName>Creative_Hub_Id__c</fullName>
    <label>Creative Hub Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Creative_Hub_Status__c.field-meta.xml
<CustomField>
    <fullName>Creative_Hub_Status__c</fullName>
    <label>Creative Hub Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>InProgess</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IntegratedEnquiry__c.field-meta.xml
<CustomField>
    <fullName>IntegratedEnquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Integrated Enquiry</label>
    <referenceTo>IntegratedEnquiry__c</referenceTo>
    <relationshipLabel>Enquiries (Integrated Enquiry)</relationshipLabel>
    <relationshipName>Enquiries1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Pitch_Presentation_Status__c.field-meta.xml
<CustomField>
    <fullName>Pitch_Presentation_Status__c</fullName>
    <label>Pitch Presentation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Creative_Hub_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Proposal_Status__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Status__c</fullName>
    <label>Proposal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Creative_Hub_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Creative_Hub_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>InProgress</fullName>
    </customValue>
    <customValue>
        <fullName>Pipeline</fullName>
    </customValue>
    <customValue>
        <fullName>Delete</fullName>
    </customValue>
    <description>Value set for creative hub status (Proposal &amp; pitchdeck status on integrated Enquiry and  Enquiry)</description>
    <masterLabel>Creative Hub Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/updateEquiryStatusWithDocApi.cls
@RestResource(urlMapping='/updateEquiryStatusWithDocApi/*')
global class updateEquiryStatusWithDocApi{
    @HTTPPUT
    global static string doPut(){
        Savepoint sp = Database.setSavepoint();
        
        try{
            RestRequest req = RestContext.request;
            blob body = req.requestBody;
            string RequestString = body.toString();
            string FinalDocumentName;
            system.debug('requested string'+RequestString);
            JsonForFinalStatusUpdateOnEnquiry jsondata = parse(RequestString);
            List<ID> listOfEnquiryIds = jsondata.childEnquiryIds.split(',');
            System.debug('listOfEnquiryIds'+listOfEnquiryIds);
            List<Opportunity> listEnquiryRecords=[Select Id,Creative_Hub_Status__c,Creative_Hub_Id__c from opportunity Where id IN :listOfEnquiryIds];
            List<IntegratedEnquiry__c> IntegratedEnquiryRecord=[Select id,Creative_Hub_Id__c, Creative_Hub_Status__c from IntegratedEnquiry__c Where Id=:jsondata.IntegratedEnquiryId limit 1];
            For(IntegratedEnquiry__c IntegratedEnquiryRec:IntegratedEnquiryRecord){
                if(jsondata.typeofDocument=='Pitch Presentation'){
                    IntegratedEnquiryRec.Pitch_Presentation_Status__c=jsondata.Creative_Hub_Status;
                    IntegratedEnquiryRec.Creative_Hub_Id__c= jsondata.Creative_Hub_ID;
                }else if(jsondata.typeofDocument=='Proposal'){
                    IntegratedEnquiryRec.Proposal_Status__c=jsondata.Creative_Hub_Status;
                    IntegratedEnquiryRec.Creative_Hub_Id__c= jsondata.Creative_Hub_ID;   
                }
            }
            database.update(IntegratedEnquiryRecord);
            For(Opportunity opp:listEnquiryRecords){
                if(jsondata.typeofDocument=='Pitch Presentation'){
                    FinalDocumentName='Pitch Deck';
                    opp.Pitch_Presentation_Status__c=jsondata.Creative_Hub_Status;
                    opp.Creative_Hub_Id__c= jsondata.Creative_Hub_ID;
                }else if(jsondata.typeofDocument=='Proposal'){
                    FinalDocumentName='Proposal';
                    opp.Proposal_Status__c=jsondata.Creative_Hub_Status;
                    opp.Creative_Hub_Id__c= jsondata.Creative_Hub_ID;   
                }
                
            }
            Database.update(listEnquiryRecords);
            if(jsondata.binaryFile!=NULL){
                
                ContentVersion cv = createContentVersion(jsondata.binaryFile, FinalDocumentName,jsondata.IntegratedEnquiryId,jsondata.typeofDocument);
                return 'Successfully Uploded';
            }else{
                return 'Successfully Updated';
            }
        }catch(exception e){
            Database.rollback( sp );
            return 'Record Not Updated';
            
            
        }
    }
    
    public static JsonForFinalStatusUpdateOnEnquiry parse(String json) {
        return (JsonForFinalStatusUpdateOnEnquiry)System.JSON.deserialize(json, JsonForFinalStatusUpdateOnEnquiry.class);
    }
    
    public class JsonForFinalStatusUpdateOnEnquiry {
        public String Creative_Hub_Status;
        public String Creative_Hub_ID;
        public String IntegratedEnquiryId;
        public string childEnquiryIds;   
        public string binaryFile;
        public string typeofDocument;
    }
    private static ContentVersion createContentVersion(String base64, String filename, string idd,string docType) {
        Id contentDocumentId;
        ContentVersion cv = new ContentVersion();
        List<ContentVersion> contver;
        string finalFileName=filename;
        finalFileName=finalFileName+'.Pdf';
        system.debug('size'+[SELECT Id, ContentDocumentId , title,filetype,fileextension, IsLatest,FirstPublishLocationId  FROM ContentVersion
                             where title =:filename and FirstPublishLocationId=:idd LIMIT 1].size());
        if(docType=='Proposal'){
            contver=[SELECT Id, ContentDocumentId , title,filetype,fileextension, IsLatest,FirstPublishLocationId  FROM ContentVersion
                     where TypeOfFile__c='Proposal'and FirstPublishLocationId=:idd LIMIT 1];
        }else if(docType=='Pitch Presentation'){
            contver=[SELECT Id, ContentDocumentId ,fileextension, IsLatest,FirstPublishLocationId,TypeOfFile__c    FROM ContentVersion
                     where TypeOfFile__c='Pitch Deck' and FirstPublishLocationId=:idd LIMIT 1];
        }
        if(contver.size()!=0){
            
            contentDocumentId = [SELECT Id, ContentDocumentId , title,filetype,fileextension, IsLatest,FirstPublishLocationId  FROM ContentVersion
                                 where title =:filename and FirstPublishLocationId=:idd LIMIT 1].ContentDocumentId;
            
            cv.VersionData = EncodingUtil.base64Decode(base64);
            cv.Title = filename;    
            cv.PathOnClient = finalFileName;
            cv.TypeOfFile__c=filename;
            cv.ContentDocumentId=contentDocumentId;
            
        }else{
            cv.VersionData = EncodingUtil.base64Decode(base64);
            cv.Title = filename;
            cv.IsMajorVersion = true; 
            cv.TypeOfFile__c=filename;
            cv.FirstPublishLocationId=idd;     
            cv.PathOnClient = finalFileName;
        }    
        try {
            insert cv;
            return cv;
        } catch(DMLException e) {
            System.debug(e);
            return null;
        }
    }
    
}