force-app/main/default/objects/Expertise_mapping_with_Sub_Expertise__mdt/Expertise_mapping_with_Sub_Expertise__mdt.object-meta.xml
<CustomObject>
    <description>Expertises mapped with sub-expertises</description>
    <label>Expertise mapping with Sub-Expertise</label>
    <pluralLabel>Expertise mapping with Sub-Expertises</pluralLabel>
</CustomObject>

force-app/main/default/objects/Expertise_mapping_with_Sub_Expertise__mdt/fields/Experties__c.field-meta.xml
<CustomField>
    <fullName>Experties__c</fullName>
    <label>Experties</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Expertise_mapping_with_Sub_Expertise__mdt/fields/Sub_Expertise__c.field-meta.xml
<CustomField>
    <fullName>Sub_Expertise__c</fullName>
    <label>Sub Expertise</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/UpdateProfessionalServicesController.cls
public class UpdateProfessionalServicesController {
   @AuraEnabled
   public static List<String> apexSubExpertise(Id leadId , String expertisePick){
       System.debug('leadId===>' + leadId);
       System.debug('expertisePick===>' + expertisePick);
       List<String> listToReturn = new List<String>();
    try {     
        for(Expertise_mapping_with_Sub_Expertise__mdt expertiMetaData : [SELECT Experties__c,Sub_Expertise__c FROM Expertise_mapping_with_Sub_Expertise__mdt WHERE Experties__c =: expertisePick.split(';')]){
            listToReturn.add(expertiMetaData.Sub_Expertise__c);
        System.debug('expertiMetaData====>' + expertiMetaData);
        }
        
    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
       System.debug('listToReturn ' + listToReturn);
    return listToReturn;
   }
}