force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <label>Enquiry</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/WCGT_Job_ID__c.field-meta.xml
<CustomField>
    <fullName>WCGT_Job_ID__c</fullName>
    <externalId>true</externalId>
    <label>WCGT Job ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PM_ACCT_INVOICE_HD__x/PM_ACCT_INVOICE_HD__x.object-meta.xml
<CustomObject>
    <description>PM_ACCT_INVOICE_HD</description>
    <externalDataSource>WCGT_Integration</externalDataSource>
    <externalName>PM_ACCT_INVOICE_HD</externalName>
    <label>PM_ACCT_INVOICE_HD</label>
    <pluralLabel>PM_ACCT_INVOICE_HD</pluralLabel>
</CustomObject>

force-app/main/default/objects/PM_ACCT_INVOICE_HD__x/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <externalDeveloperName>PROJECT_ID</externalDeveloperName>
    <label>Job</label>
    <length>255</length>
    <referenceTargetField>Job__c.WCGTProjectID__c</referenceTargetField>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>PM_ACCT_INVOICE_HD</relationshipLabel>
    <relationshipName>PM_ACCT_INVOICE_HD</relationshipName>
    <type>IndirectLookup</type>
</CustomField>

force-app/main/default/classes/BillingInformationOnEnquiry.cls
public class BillingInformationOnEnquiry {

    @AURAENABLED(CACHEABLE=TRUE)
    public static List<wrpInvoiceData> getInvoiceListforJob(string enquiryId){
        set<String> wcgtJobId = new set<String>();
        List<Opportunity> oppList = [select Id,AccountId,Account.Name,WCGT_Job_ID__c 
                                     from Opportunity where AccountId =:enquiryId];
        List<wrpInvoiceData> wrpInvList = new List<wrpInvoiceData>();
        for(Opportunity opp:oppList){
            wcgtJobId.add(opp.WCGT_Job_ID__c);
        }
        if(wcgtJobId != null){
            for(PM_ACCT_INVOICE_HD__x inv:[SELECT Id,INVOICE_DATE__c,NET_AMT__c,INVOICE_TYPE__c,PROJECT_ID__c 
                                           FROM PM_ACCT_INVOICE_HD__x where PROJECT_ID__c in:wcgtJobId]){
               wrpInvoiceData wrpInv = new wrpInvoiceData();
                wrpInv.InvoiceType=inv.INVOICE_TYPE__c;
                wrpInv.InvoiceDate=inv.INVOICE_DATE__c;
                wrpInv.InvoiceAMount=inv.NET_AMT__c;
                wrpInvList.add(wrpInv);
            } 
        }
        if(wrpInvList.size()>0){
            return wrpInvList;
        }else{
            return null;
        }
        /*set<Id> jobId = new set<Id>();
        for(Job__c j:[select Id from Job__c where Enquiry__c =:enquiryId]){
         		jobId.add(j.Id);   
        }
        
        if(jobId != null){
         	return [SELECT Id,INVOICE_DATE__c,NET_AMT__c FROM PM_ACCT_INVOICE_HD__x limit 5/*where PROJECT_ID__c in:jobId*//*];   
        }else{
            return null;
        }*/
    } 
    
    public class wrpInvoiceData{
        @auraEnabled
        public string InvoiceType{get;set;}
        @AuraEnabled    
        public Decimal InvoiceAMount{get;set;}
        @AuraEnabled
        public DateTime InvoiceDate{get;set;}
    }
}