force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Client_News__c/Client_News__c.object-meta.xml
<CustomObject>
    <label>Client News</label>
    <nameField>
        <label>Client News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_News__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Newss</relationshipLabel>
    <relationshipName>Client_Newss</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_News__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Client Newss</relationshipLabel>
    <relationshipName>Client_Newss</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_News__c/fields/New_Client__c.field-meta.xml
<CustomField>
    <fullName>New_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Client</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Client News</relationshipLabel>
    <relationshipName>Client_Newss</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/KeyDevAndAlertsController.cls
/*
 * Author : Suraj Kumar
 * Date : 20-01-2023
 * Description : Controller class for Key development and Alerts LWC
 * Last Updated By :- Bhanwar 
 * Last Update Discription :- Added for Enquiry so we can get all the news related to that client
*/
public With Sharing class KeyDevAndAlertsController {
    
    @AuraEnabled
    public static List<Client_News__c> getNewClient(String recordId, String objectName){
        if(objectName == 'Lead'){
            Lead lead = [SELECT Id, Name, capIQId__c, (SELECT Id, Name, IQ_KEY_DEV_HEADLINE__c FROM Client_Newss__r ) FROM Lead WHERE Id =: recordId With Security_Enforced];
            
            if(!lead.Client_Newss__r.isEmpty() && lead.capIQId__c != Null){
                return lead.Client_Newss__r;
            }
            else{
                return null;
            }
        }
        else if(objectName == 'Account'){
            Account acc = [SELECT Id, Name, capIQId__c, (SELECT Id, Name, IQ_KEY_DEV_HEADLINE__c FROM Client_Newss__r) FROM Account WHERE Id =: recordId With Security_Enforced];
            
            if(!acc.Client_Newss__r.isEmpty() && acc.capIQId__c != Null){
                return acc.Client_Newss__r;
            }
            else{
                return null;
            }
        }
        /*else if(objectName == 'Opportunity'){
            Opportunity opp = [SELECT Id, Name, capIQId__c, (SELECT Id, Name, IQ_KEY_DEV_HEADLINE__c FROM Client_Newss__r) FROM Opportunity WHERE Id =: recordId];
            System.debug('Opportunity : ' + opp.Client_Newss__r);
            
            if(!opp.Client_Newss__r.isEmpty() && opp.capIQId__c != Null){
                return opp.Client_Newss__r;
            }
            else{
                return null;
            }
        }*/
        // By Bhanwar 24/04/23
        else if(objectName == 'Opportunity'){
            Opportunity opp = [SELECT Id, AccountId FROM Opportunity WHERE Id =: recordId With Security_Enforced];
            Account acc = [SELECT Id, Name, capIQId__c, (SELECT Id, Name, IQ_KEY_DEV_HEADLINE__c FROM Client_Newss__r) FROM Account WHERE Id =: opp.AccountId With Security_Enforced];
            
            if(!acc.Client_Newss__r.isEmpty() && acc.capIQId__c != Null){
                return acc.Client_Newss__r;
            }
            else{
                return null;
            }
        }
        else{
            return null;
        }
        
    }
    
    
}