force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Lead/fields/CCApprovalRejectionRecommendation__c.field-meta.xml
<CustomField>
    <fullName>CCApprovalRejectionRecommendation__c</fullName>
    <description>It depicts the Approval / Rejection recommendation status.</description>
    <inlineHelpText>Client Council Recommendations</inlineHelpText>
    <label>CC_Approval / Rejection Recommendation</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ClientBackground__c.field-meta.xml
<CustomField>
    <fullName>ClientBackground__c</fullName>
    <description>It depicts Client Background.</description>
    <inlineHelpText>Highest level parent within a corporate family tree that is domiciled in the same country</inlineHelpText>
    <label>Client Background</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <description>This is having details of GT Expertise.</description>
    <label>Expertise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Solution__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/HowDidYouArriveAThisTentativeFee__c.field-meta.xml
<CustomField>
    <fullName>HowDidYouArriveAThisTentativeFee__c</fullName>
    <label>How did you arrive at this tentative fee</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/NSL__c.field-meta.xml
<CustomField>
    <fullName>NSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It depicts which user has referred this lead.</description>
    <label>NSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/NSLApprovalRejectionRecommendation__c.field-meta.xml
<CustomField>
    <fullName>NSLApprovalRejectionRecommendation__c</fullName>
    <label>NSL Approval / Rejection Recommendation</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/NSLApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>NSLApprovalStatus__c</fullName>
    <label>NSL Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <description>This is having all the sector details of GT.</description>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ShortSummary__c.field-meta.xml
<CustomField>
    <fullName>ShortSummary__c</fullName>
    <inlineHelpText>Provide a short summary about the professional services required, or any additional remarks regarding the client</inlineHelpText>
    <label>Summary (Challenges, Opportunities etc)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SubExpertise__c.field-meta.xml
<CustomField>
    <fullName>SubExpertise__c</fullName>
    <description>It contains the information of sub expertise related to particular expertise.</description>
    <label>SMEG</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SubExpertise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/TentativeFee__c.field-meta.xml
<CustomField>
    <fullName>TentativeFee__c</fullName>
    <inlineHelpText>Information regarding new client from GT Website</inlineHelpText>
    <label>Tentative Fee</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Auto &amp; Auto Components</fullName>
    </customValue>
    <customValue>
        <fullName>CIP &amp; Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>Global Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Law Firms</fullName>
    </customValue>
    <customValue>
        <fullName>Owners &amp; Private Clients</fullName>
    </customValue>
    <customValue>
        <fullName>PE/VC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma &amp; Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate &amp; Infra</fullName>
    </customValue>
    <customValue>
        <fullName>TMT</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Sector</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SubExpertise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Attest Services</fullName>
    </customValue>
    <customValue>
        <fullName>BFSI Tax</fullName>
    </customValue>
    <customValue>
        <fullName>Business Intelligence and Information Management (BIIM)</fullName>
    </customValue>
    <customValue>
        <fullName>Compliance &amp; Outsourcing</fullName>
    </customValue>
    <customValue>
        <fullName>Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Intelligence</fullName>
    </customValue>
    <customValue>
        <fullName>Customer, marketing and sales</fullName>
    </customValue>
    <customValue>
        <fullName>CYBER</fullName>
    </customValue>
    <customValue>
        <fullName>DGTL</fullName>
    </customValue>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Digital CoE</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Tax</fullName>
    </customValue>
    <customValue>
        <fullName>Due Diligence</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Transformation and Optimisation</fullName>
    </customValue>
    <customValue>
        <fullName>ESG</fullName>
    </customValue>
    <customValue>
        <fullName>Forensic</fullName>
    </customValue>
    <customValue>
        <fullName>FRAS</fullName>
    </customValue>
    <customValue>
        <fullName>FS Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>FS Risk</fullName>
    </customValue>
    <customValue>
        <fullName>GD AUS</fullName>
    </customValue>
    <customValue>
        <fullName>GDUK</fullName>
    </customValue>
    <customValue>
        <fullName>GDUSA</fullName>
    </customValue>
    <customValue>
        <fullName>Global Audit Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Global Mobility Services</fullName>
    </customValue>
    <customValue>
        <fullName>Global Tax Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Governance Risk &amp; Operations (GRO)</fullName>
    </customValue>
    <customValue>
        <fullName>GRC</fullName>
    </customValue>
    <customValue>
        <fullName>GT International</fullName>
    </customValue>
    <customValue>
        <fullName>GTUSA</fullName>
    </customValue>
    <description>It contains the information of sub expertise related to particular expertise</description>
    <masterLabel>Sub Expertise</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeadTriggerHandlerTest.cls
/*
*Author : Gaurav Kumar 
*Description :LeadTriggerHandler 
*Date :13/12/2022 
*/
@isTest
public class LeadTriggerHandlerTest {
    @isTest
    public static void test(){
        List<Lead> leadList = new List<Lead>();
        Map<Id ,Lead> oldLeadMap = new Map<Id ,Lead>();
        
        Account acc = new Account(Name = 'Test');
        
        Profile pro = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        User u = new user();
        u.LastName = 'Testclassra Code';
        u.Email = 'test@test.com';
        u.Alias = 'Tcode';
        u.Username = 'testclasshhhy@test.com';
        u.CommunityNickname = 'test12';
        u.LocaleSidKey = 'en_US';
        u.TimeZoneSidKey = 'GMT';
        u.ProfileId = pro.Id;
        u.LanguageLocaleKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        insert u;
        
        
        
        Lead obj = new Lead();
        obj.LastName = 'Test';
        obj.Sector__c = 'Government';
        obj.NSL__c = u.Id;
        obj.Status = 'Client Take-On PreWork';
        obj.Company = 'TMC';
        obj.Email = 'test@gmail.com';
        obj.MobilePhone = '1234567891';
        insert obj;
        
        Lead obj1 = new Lead();
        obj1.LastName = 'Test';
        obj1.NSLApprovalStatus__c = 'Approved';
        obj1.Status = 'Internal / External Discussions';
        obj1.CCApprovalStatus__c = 'Approved';
        obj1.OnNewStage__c = 2323;
        obj1.Expertise__c = 'Forensic';
        obj1.SubExpertise__c = 'Cyber';
        obj1.Region__c = 'North';
        obj1.NSLApprovalRejectionRecommendation__c = 'fgnc';
        obj1.Company = 'TMC';
        obj1.NSL__c = u.Id;
        obj1.OwnerId = u.Id;
        obj1.Expertise__c = '';
        obj1.CCApprovalRejectionRecommendation__c= 'sdfsdf';
        obj1.ClientBackground__c = 'sdasd';
        obj1.GrowthPotential__c = 'fdsdf';
        obj1.TentativeFee__c =123;
        obj1.HowDidYouArriveAThisTentativeFee__c = 'dasd';
        obj1.ShortSummary__c = 'sdfsad';
        //obj1.CreatedDate = datetime.newInstance('2022', '12', '13');
        obj1.Sector__c = 'Government';
        obj1.Email = 'test@gmail.com';
        obj1.MobilePhone = '1234567891';
        insert obj1;
        leadList.add(obj1);
        obj1.CCApprovalRejectionRecommendation__c = 'Test';
        update obj1;
        oldLeadMap.put(obj1.Id ,obj1);
        obj1.NSLApprovalRejectionRecommendation__c = 'fgfsdfnc';
        update obj1;
        //insert leadList;
        List<Task> taskList = new List<Task>();
        Task objTask = new Task();
        objTask.Subject = 'Next steps & actions discussed with NSL';
        objTask.WhoId = obj1.Id;
        objTask.CurrencyIsoCode = '';
        objTask.OwnerId = u.Id;
        insert objTask;
        //ProcessInstance pi = [SELECT TargetObjectId, CreatedDate FROM ProcessInstance WHERE TargetObjectId = :acc.Id];
        
        Approval.ProcessSubmitRequest req1 =
            new Approval.ProcessSubmitRequest();
        req1.setComments('Approved.');
        req1.setNextApproverIds(new Id[]{UserInfo.getUserId()});
        
        req1.setObjectId(obj1.id);//Set the record Id
        
        // Submit on behalf of a specific submitter
        req1.setSubmitterId(UserInfo.getUserId());
        
        // Submit the record to specific process and skip the criteria evaluation
        req1.setProcessDefinitionNameOrId('');//set the name of your approval process
        req1.setSkipEntryCriteria(true);
        // Submit the approval request for the account
        Approval.ProcessResult result = Approval.process(req1);
        
        
        //Step for approving by user 1st
        Approval.ProcessWorkitemRequest req2 =  new Approval.ProcessWorkitemRequest();
        req2.setComments('Approving request.');
        req2.setAction('Approve');
        req2.setNextApproverIds(new Id[] {UserInfo.getUserId()});//UserInfo.getUserId()
        system.debug('req2::'+req2);
        // Use the ID from the newly created item to specify the item to be worked
        req2.setWorkitemId(result.getNewWorkitemIds().get(0));
        system.debug('req3::'+req2);
        // Submit the request for approval
        Approval.ProcessResult result2 =  Approval.process(req2);
        
        Test.startTest();
        LeadTriggerHandler.isAfterUpdateMethod(leadList , oldLeadMap);
        //LeadTriggerHandler.AgingOfStage(leadList);
        LeadTriggerHandler.updateApprovalFieldsOfNSLOnEnquiry(leadList);
        LeadTriggerHandler.updateApprovalFieldsOfCCOnEnquiry(leadList);
        Test.stopTest(); 
        
    }
   
}