force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case Support</businessProcess>
    <label>Case</label>
</RecordType>

force-app/main/default/objects/Lead/fields/NSL__c.field-meta.xml
<CustomField>
    <fullName>NSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It depicts which user has referred this lead.</description>
    <label>NSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <description>This is having all the sector details of GT.</description>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SectorCoordinator__c.field-meta.xml
<CustomField>
    <fullName>SectorCoordinator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sector Business Partner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>New_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sector_cordinator__mdt/sector_cordinator__mdt.object-meta.xml
<CustomObject>
    <label>sector cordinator</label>
    <pluralLabel>sector cordinators</pluralLabel>
</CustomObject>

force-app/main/default/objects/sector_cordinator__mdt/fields/NSL__c.field-meta.xml
<CustomField>
    <fullName>NSL__c</fullName>
    <inlineHelpText>Please Populate the Federation Identifier of NSL from User record.</inlineHelpText>
    <label>NSL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sector_cordinator__mdt/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sector_cordinator__mdt/fields/sector_cordinator_id__c.field-meta.xml
<CustomField>
    <fullName>sector_cordinator_id__c</fullName>
    <inlineHelpText>Please Populate the Federation Identifier of Sector Business Partner from User record.</inlineHelpText>
    <label>sector cordinator id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Auto &amp; Auto Components</fullName>
    </customValue>
    <customValue>
        <fullName>CIP &amp; Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>Global Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Law Firms</fullName>
    </customValue>
    <customValue>
        <fullName>Owners &amp; Private Clients</fullName>
    </customValue>
    <customValue>
        <fullName>PE/VC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma &amp; Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate &amp; Infra</fullName>
    </customValue>
    <customValue>
        <fullName>TMT</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Sector</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/checkDuplicateClientOnLeadCreation.cls
/*
Written By: Rohitash mourya
Created Date:  10/10/2022
Last Modified By : Rohitash mourya
Last Modified Date : 23-03-23
Description : This class is used to Assigned Sector bussines partner and NSL in case of manual new lead creation
*/
public with sharing class checkDuplicateClientOnLeadCreation {
    public static void checkDuplicateClient(list<Lead> leadRecord){
      /*  List<Account> clientrecord=[Select Name From Account Where name=:leadRecord[0].Company];
       // Map<String,sector_cordinator__mdt> sector = [select id,label,sector_cordinator_id__c,NSL__C,Sector__c from sector_cordinator__mdt];
       Map<string,sector_cordinator__mdt> sector=sector_cordinator__mdt.getAll();
        
        system.debug('Sector metadata'+sector);
        String sectorFedId;
        String nslFedId;
        User nslUser;
        user sectorBUser;
        system.debug('Lead Record 18'+leadRecord);
       
        for(lead lrecord:leadRecord){
            system.Debug('Sector Name'+lrecord.Sector__c);
            system.debug('Sector metadata'+sector.get(lrecord.Sector__c));
            if(lrecord.Sector__c != NULL && lrecord.Sector__c != '' && sector.get(lrecord.Sector__c)!=Null)
            {
                sectorFedId=sector.get(lrecord.Sector__c).sector_cordinator_id__c;
                nslFedId=sector.get(lrecord.Sector__c).NSL__C;
                
            }
            
        }
        nslUser=[select name,FederationIdentifier,Id from user where FederationIdentifier =:nslFedId Limit 1];
        sectorBUser=[select name,FederationIdentifier,Id from user where FederationIdentifier =:sectorFedId Limit 1];
        
        for(lead lrecord:leadRecord){
            if(lrecord.Sector__c != NULL && lrecord.Sector__c != '')
            {
                lrecord.SectorCoordinator__c= nslUser.Id;
                lrecord.NSL__c=sectorBUser.Id ;
            }
            
        }
        
        
        system.debug('clientrecord'+clientrecord);
        /* if(clientrecord.size()!=0){
for(lead lrecord:leadRecord){
system.debug('error');
lrecord.adderror('Client Already Exist With Similar Name');   
}

}*/
        
    }
    
    
}