force-app/main/default/objects/Account/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <label>Client Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key Account - CX</fullName>
            </value>
            <value>
                <fullName>Key Account - GX</fullName>
            </value>
            <value>
                <fullName>Non Key Client</fullName>
                <default>true</default>
                <label>Non Key Client</label>
            </value>
            <value>
                <fullName>Apex Chambers</fullName>
            </value>
            <value>
                <fullName>Bilateral Chamber</fullName>
            </value>
            <value>
                <fullName>Sectoral Chamber</fullName>
            </value>
            <value>
                <fullName>Regional &amp; Other Chamber</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CoCSL__c.field-meta.xml
<CustomField>
    <fullName>CoCSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-CSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CSL__c.field-meta.xml
<CustomField>
    <fullName>CSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ReminderAccountPlanBatchHelper.cls
/*
 * Author : Suraj Kumar
 * Date : 21-12-2022
 * Description : Helper class of ReminderAccountPlanBatch
*/

public class ReminderAccountPlanBatchHelper {
    public static String getQuery(){
        String query = 'SELECT Id, Name, Account_Plan_Status__c, AccountType__c, CSL__r.Email, CoCSL__r.Email, NSL__r.Email, CreatedDate  FROM Account WHERE (Account_Plan_Status__c = \'Draft\' OR Account_Plan_Status__c = \'Pending NSL Approval\') AND (AccountType__c = \'Key Account - CX\' OR AccountType__c = \'Key Account - GX\' )';
        return query;
    }
}