force-app/main/default/objects/Account/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <label>Client Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key Account - CX</fullName>
            </value>
            <value>
                <fullName>Key Account - GX</fullName>
            </value>
            <value>
                <fullName>Non Key Client</fullName>
                <default>true</default>
                <label>Non Key Client</label>
            </value>
            <value>
                <fullName>Apex Chambers</fullName>
            </value>
            <value>
                <fullName>Bilateral Chamber</fullName>
            </value>
            <value>
                <fullName>Sectoral Chamber</fullName>
            </value>
            <value>
                <fullName>Regional &amp; Other Chamber</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CSL__c.field-meta.xml
<CustomField>
    <fullName>CSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Recovery__c.field-meta.xml
<CustomField>
    <fullName>Recovery__c</fullName>
    <formula>( ClosedWonAmount__c   -   TotalExpenses__c  )/   ClosedWonAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Recovery%</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Lead/fields/ClientContact__c.field-meta.xml
<CustomField>
    <fullName>ClientContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It depicts which Client Contact has referred this Lead.</description>
    <inlineHelpText>Referral from existing client contact</inlineHelpText>
    <label>Client Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ClientName__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CSL__c.field-meta.xml
<CustomField>
    <fullName>CSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/NSLApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>NSLApprovalStatus__c</fullName>
    <label>NSL Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CCApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>CCApprovalStatus__c</fullName>
    <label>CC_Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSL__c.field-meta.xml
<CustomField>
    <fullName>CSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSLApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>NSLApprovalStatus__c</fullName>
    <label>NSLApprovalStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Recovery__c.field-meta.xml
<CustomField>
    <fullName>Recovery__c</fullName>
    <label>Recovery%</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/SubmitForApprovalButtonController.cls
public without sharing class SubmitForApprovalButtonController {
    @AuraEnabled
    public static void sendEnquiryApprovalRequest(String recordId,String assignApproval,String comments){
        System.debug('Hello Testing ');
        List<Lead> leadList = [select id from Lead where Id =:recordId];
        String userId = UserInfo.getUserId();
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments(comments);
        req1.setObjectId(recordId);
        System.debug(userId);
        req1.setSubmitterId(userId); 
        req1.setProcessDefinitionNameOrId(assignApproval);
        req1.setSkipEntryCriteria(true);
        try{
            Approval.ProcessResult result = Approval.process(req1);
            if(assignApproval=='NSL_Approval'){
                leadList[0].NSLApprovalStatus__c = 'Pending';  
            }
            else if(assignApproval=='ClientCouncilApproval'){
                leadList[0].CCApprovalStatus__c = 'Pending';
            }
            update leadList;
        }
        catch(Exception e){
            System.debug('Error occured '+e.getMessage()+' '+e.getLineNumber());
        }
    }
    @AuraEnabled
    public static void sendOpportunityApprovalRequest(String recordId,String assignApproval,String comments){
        List<Opportunity> oppoList = [select id,AccountId,ClientContact__c from Opportunity where Id =:recordId];
        String accountid = oppoList[0].AccountId;
        String contactId;
        if(oppoList[0].ClientContact__c!=null){
            contactId = oppoList[0].ClientContact__c;
        }
        String userId = UserInfo.getUserId();
        String assignAccountApproval = 'DS_Team_Account_Approval';
        String assignContactApproval = 'DS_Team_Contact_Approval';
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments(comments);
        req1.setObjectId(recordId);
        System.debug(userId);
        req1.setSubmitterId(userId); 
        req1.setProcessDefinitionNameOrId(assignApproval);
        req1.setSkipEntryCriteria(true);
        try{
            Approval.ProcessResult result = Approval.process(req1);
            if(assignApproval=='DS_Team_Approval'){
                oppoList[0].StatusDSTeamRemarkStatus__c = 'Pending';
            }
            update oppoList;
        }
        catch(Exception e){
            System.debug('Error occured '+e.getMessage()+' '+e.getLineNumber());
        }
        System.debug('account id'+accountid+'account approval'+assignAccountApproval+'comments'+comments);
        if(accountid!=null && assignAccountApproval!=null ){
           // sendAccountApprovalRequest(accountid,assignAccountApproval,comments);
        }
        if(assignContactApproval!=null && contactId !=null){
           // sendContactApprovalRequest(contactId,assignContactApproval,comments);
        }
    }
    @AuraEnabled
    public static void sendAccountApprovalRequest(String accountid,String assignApproval,String comments){
        String userId = UserInfo.getUserId();
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments(comments);
        req1.setObjectId(accountid);
        System.debug(userId);
        req1.setSubmitterId(userId); 
        req1.setProcessDefinitionNameOrId(assignApproval);
        req1.setSkipEntryCriteria(true);
        try{
            Approval.ProcessResult result = Approval.process(req1);
            /*if(assignApproval=='DS_Team_Approval'){
oppoList[0].StatusDSTeamRemarkStatus__c = 'Pending';
}
update oppoList;*/
        }
        catch(Exception e){
            System.debug('Error occured '+e.getMessage()+' '+e.getLineNumber());
        }
    }
    @AuraEnabled
    public static void sendContactApprovalRequest(String contactId,String assignApproval,String comments){
        String userId = UserInfo.getUserId();
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments(comments);
        req1.setObjectId(contactId);
        System.debug(userId);
        req1.setSubmitterId(userId); 
        req1.setProcessDefinitionNameOrId(assignApproval);
        req1.setSkipEntryCriteria(true);
        try{
            Approval.ProcessResult result = Approval.process(req1);
            /*if(assignApproval=='DS_Team_Approval'){
oppoList[0].StatusDSTeamRemarkStatus__c = 'Pending';
}
update oppoList;*/
        }
        catch(Exception e){
            System.debug('Error occured '+e.getMessage()+' '+e.getLineNumber());
        }
    }
    public static void sendQuoteApprovalRequest(String recordId){
        List<Quote> quoteList = [select id,Opportunity.Account.AccountType__c,Opportunity.CSL__c,Opportunity.Account.Recovery__c
                                 from Quote where Id =:recordId];
        String userId = UserInfo.getUserId();
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(recordId);
        System.debug(userId);
        req1.setSubmitterId(userId); 
        req1.setProcessDefinitionNameOrId('Quote_Approval');
        req1.setSkipEntryCriteria(true);
        try{
            if(quoteList[0].Status=='Internal Review'){
                if(quoteList[0].Opportunity.Account.AccountType__c=='Key Client'){
                    req1.setNextApproverIds(new Id[] {quoteList[0].Opportunity.CSL__c});
                }
                else if(quoteList[0].Opportunity.Account.AccountType__c=='New Client' && quoteList[0].Opportunity.Account.Recovery__c>70){
                    req1.setNextApproverIds(new Id[] {quoteList[0].Opportunity.CSL__c});
                }
                else if(quoteList[0].Opportunity.Account.AccountType__c=='New Client' && quoteList[0].Opportunity.Account.Recovery__c<70){
                    req1.setNextApproverIds(new Id[] {quoteList[0].Opportunity.CSL__c});  
                }
            }
            Approval.ProcessResult result = Approval.process(req1);
        }
        catch(Exception e){
            System.debug('Error occured '+e.getMessage()+' '+e.getLineNumber());
        }
    }
    public static void sendProposedAccountOwnerApproval(String recordId,String assignApproval,String comments){
        List<Account> acctList = [select id,Proposed_Account_Owner_Approval_Status__c from Account where Id =:recordId];
        String userId = UserInfo.getUserId();
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments(comments);
        req1.setObjectId(recordId);
        System.debug(userId);
        req1.setSubmitterId(userId); 
        req1.setProcessDefinitionNameOrId(assignApproval);
        req1.setSkipEntryCriteria(true);
        try{
            Approval.ProcessResult result = Approval.process(req1);
            if(assignApproval=='Proposed_Account_Owner_Approval_Request'){
                acctList[0].Proposed_Account_Owner_Approval_Status__c = 'Pending';
            }
            update acctList;
        }
        catch(Exception e){
            System.debug('Error occured '+e.getMessage()+' '+e.getLineNumber());
        }
    } 
}