force-app/main/default/objects/Account/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <label>Client Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key Account - CX</fullName>
            </value>
            <value>
                <fullName>Key Account - GX</fullName>
            </value>
            <value>
                <fullName>Non Key Client</fullName>
                <default>true</default>
                <label>Non Key Client</label>
            </value>
            <value>
                <fullName>Apex Chambers</fullName>
            </value>
            <value>
                <fullName>Bilateral Chamber</fullName>
            </value>
            <value>
                <fullName>Sectoral Chamber</fullName>
            </value>
            <value>
                <fullName>Regional &amp; Other Chamber</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CSL__c.field-meta.xml
<CustomField>
    <fullName>CSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Recovery__c.field-meta.xml
<CustomField>
    <fullName>Recovery__c</fullName>
    <formula>( ClosedWonAmount__c   -   TotalExpenses__c  )/   ClosedWonAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Recovery%</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Contact/fields/NSL__c.field-meta.xml
<CustomField>
    <fullName>NSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ClientContact__c.field-meta.xml
<CustomField>
    <fullName>ClientContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It depicts which Client Contact has referred this Lead.</description>
    <inlineHelpText>Referral from existing client contact</inlineHelpText>
    <label>Client Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.ClientName__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CSL__c.field-meta.xml
<CustomField>
    <fullName>CSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/NSL__c.field-meta.xml
<CustomField>
    <fullName>NSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It depicts which user has referred this lead.</description>
    <label>NSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSL__c.field-meta.xml
<CustomField>
    <fullName>CSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSL__c.field-meta.xml
<CustomField>
    <fullName>NSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OpportunitiesnN4X</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Recovery__c.field-meta.xml
<CustomField>
    <fullName>Recovery__c</fullName>
    <label>Recovery%</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/SubmitForApprovalButtonTest.cls
/*
*Author : Suraj Kumar 
*Description : Test class of SubmitForApprovalButtonController 
*Date :13/12/2022 
*/

@isTest
public class SubmitForApprovalButtonTest {
    
    @testSetup
    public static void testSetup(){
        
        Lead l = new Lead();
        l.LastName = 'TestLastttName';
        l.Company = 'TestCompany';
        l.NSL__c = UserInfo.getUserId();
        insert l;
        
        Account acc = new Account(Name='Test Account', AccountType__c = 'Key Client');
        insert acc;
        
        Contact con = new Contact(LastName='testName');
        insert con;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'TestName ';
        opp.StageName = 'Identify/Create Enquiry';
        opp.CloseDate = System.today();
        opp.AccountId = acc.Id;
        opp.ClientContact__c = con.Id;
        Test.setMock(HttpCalloutMock.class, new EnquiryTriggerMock());
        insert opp;
        
        Quote q = new Quote();
        q.Name = 'Test Quote';
        q.Status = 'Internal Review';
        q.OpportunityId = opp.Id;
        insert q;
        
        
    }
    
    @isTest
    public static void sendEnquiryApprovalRequestTest1(){
        List<User> userList = [select Id FROM User];
        List<Lead> leadList = [Select Id FROM Lead];
        List<Opportunity> oppList = [SELECT id, AccountId, OwnerId, ClientContact__c FROM Opportunity];
        List<Quote> quoteList = [select id,Opportunity.Account.AccountType__c,Opportunity.CSL__c, OpportunityId, Status, Opportunity.Account.Recovery__c
                                 from Quote];
        
        
        Test.startTest();
        
        SubmitForApprovalButtonController.sendEnquiryApprovalRequest(leadList[0].id, 'NSL_Approval' , 'Test');
        SubmitForApprovalButtonController.sendOpportunityApprovalRequest(oppList[0].id, 'DS_Team_Approval' , 'Test');
        SubmitForApprovalButtonController.sendQuoteApprovalRequest(quoteList[0].id);
        
        Test.stopTest();
        
    }
    
    @isTest
    public static void sendEnquiryApprovalRequestTest2(){
        List<User> userList = [select Id FROM User];
        List<Lead> leadList = [Select Id FROM Lead];
        List<Opportunity> oppList = [SELECT id, AccountId, OwnerId, ClientContact__c FROM Opportunity];
        
        Test.startTest();
        
        SubmitForApprovalButtonController.sendEnquiryApprovalRequest(leadList[0].id, 'ClientCouncilApproval' , 'Test');
        SubmitForApprovalButtonController.sendOpportunityApprovalRequest(oppList[0].id, 'ClientCouncilApproval' , 'Test');
        
        Test.stopTest();
        
    }
    

}