force-app/main/default/objects/Account/fields/RCCCurrentStatus__c.field-meta.xml
<CustomField>
    <fullName>RCCCurrentStatus__c</fullName>
    <label>RCC Current Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>NotInitiated</fullName>
                <label>Not Initiated</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Outstanding</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ClientName__c.field-meta.xml
<CustomField>
    <fullName>ClientName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enquiries (Client Name)</relationshipLabel>
    <relationshipName>Enquiries1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PendingDaysToExpire__c.field-meta.xml
<CustomField>
    <fullName>PendingDaysToExpire__c</fullName>
    <description>It will calculate pending days for RCC to expire.</description>
    <formula>DueDateTillExpiry__c  -  TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Remaining days till RCC expire.</inlineHelpText>
    <label>Pending Days To Expire</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RCCCurrentStatus__c.field-meta.xml
<CustomField>
    <fullName>RCCCurrentStatus__c</fullName>
    <label>RCC Current Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Initiated</fullName>
                <default>true</default>
                <label>Not Initiated</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Conflict</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Outstanding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RCC__c/RCC__c.object-meta.xml
<CustomObject>
    <label>RCC</label>
    <nameField>
        <label>Name Of Entity</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RCCs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/RCC__c/fields/ClientName__c.field-meta.xml
<CustomField>
    <fullName>ClientName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RCCs</relationshipLabel>
    <relationshipName>RCCs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RCC__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>RCCs</relationshipLabel>
    <relationshipName>RCCs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/rCCFormHelper.cls
public with sharing class rCCFormHelper {
    @AuraEnabled(cacheable=true)
    public static List<RCC__c> getRCCs(String enquiryId){
        List<Opportunity> opp = [SELECT AccountId FROM Opportunity WHERE Id =: enquiryId LIMIT 1];
        if(opp.size() > 0){
            return [SELECT Id, Name, ClientName__r.Name, Enquiry__r.Name, Enquiry__r.RCCCurrentStatus__c, CreatedDate, Enquiry__r.PendingDaysToExpire__c FROM RCC__c WHERE ClientName__c =:opp[0].AccountId WITH SECURITY_ENFORCED];
        }else{
            return [SELECT Id, Name, ClientName__r.Name, Enquiry__r.Name, Enquiry__r.RCCCurrentStatus__c, CreatedDate, Enquiry__r.PendingDaysToExpire__c FROM RCC__c WHERE Enquiry__c =:enquiryId WITH SECURITY_ENFORCED];
        }
    }
}