force-app/main/default/objects/Opportunity/fields/Calculate_Days_On_Nurture_Stage__c.field-meta.xml
<CustomField>
    <fullName>Calculate_Days_On_Nurture_Stage__c</fullName>
    <label>Calculate Days On Nurture Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Nurture_Finalizing_Closure_Date__c.field-meta.xml
<CustomField>
    <fullName>Nurture_Finalizing_Closure_Date__c</fullName>
    <label>Nurture &amp; Finalizing Closure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/SendEmailToEOBatchHelper.cls
/*
* Author :Gaurav Kumar 
* Batch Class :SendEmailToEOBatch
* Date :26/12/2022
*/
public class SendEmailToEOBatchHelper {
    public static String getQuery(){
        String query = 'Select Id,Owner.Email,Calculate_Days_On_Nurture_Stage__c,Nurture_Finalizing_Closure_Date__c,Name '+ 
            'from Opportunity '+ 'where StageName =\'Closed Won\' AND Nurture_Finalizing_Closure_Date__c!=null ';
        
        if(String.isNotBlank(query)){
            return query;
        }
        else{
            return query;
        }
    }
}