force-app/main/default/objects/Opportunity/fields/CoCSL__c.field-meta.xml
<CustomField>
    <fullName>CoCSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-CSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSL__c.field-meta.xml
<CustomField>
    <fullName>CSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSL__c.field-meta.xml
<CustomField>
    <fullName>NSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OpportunitiesnN4X</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RELBUL__c.field-meta.xml
<CustomField>
    <fullName>RELBUL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REL/BUL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Enquiries4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RMP__c.field-meta.xml
<CustomField>
    <fullName>RMP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RMP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Enquiries5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SubExpertise__c.field-meta.xml
<CustomField>
    <fullName>SubExpertise__c</fullName>
    <label>Sub Expertise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SubExpertise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/SubExpertise.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Attest Services</fullName>
    </customValue>
    <customValue>
        <fullName>BFSI Tax</fullName>
    </customValue>
    <customValue>
        <fullName>Business Intelligence and Information Management (BIIM)</fullName>
    </customValue>
    <customValue>
        <fullName>Compliance &amp; Outsourcing</fullName>
    </customValue>
    <customValue>
        <fullName>Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Intelligence</fullName>
    </customValue>
    <customValue>
        <fullName>Customer, marketing and sales</fullName>
    </customValue>
    <customValue>
        <fullName>CYBER</fullName>
    </customValue>
    <customValue>
        <fullName>DGTL</fullName>
    </customValue>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Digital CoE</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Tax</fullName>
    </customValue>
    <customValue>
        <fullName>Due Diligence</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Transformation and Optimisation</fullName>
    </customValue>
    <customValue>
        <fullName>ESG</fullName>
    </customValue>
    <customValue>
        <fullName>Forensic</fullName>
    </customValue>
    <customValue>
        <fullName>FRAS</fullName>
    </customValue>
    <customValue>
        <fullName>FS Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>FS Risk</fullName>
    </customValue>
    <customValue>
        <fullName>GD AUS</fullName>
    </customValue>
    <customValue>
        <fullName>GDUK</fullName>
    </customValue>
    <customValue>
        <fullName>GDUSA</fullName>
    </customValue>
    <customValue>
        <fullName>Global Audit Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Global Mobility Services</fullName>
    </customValue>
    <customValue>
        <fullName>Global Tax Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Governance Risk &amp; Operations (GRO)</fullName>
    </customValue>
    <customValue>
        <fullName>GRC</fullName>
    </customValue>
    <customValue>
        <fullName>GT International</fullName>
    </customValue>
    <customValue>
        <fullName>GTUSA</fullName>
    </customValue>
    <description>It contains the information of sub expertise related to particular expertise</description>
    <masterLabel>Sub Expertise</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteTriggerHandler.cls
public class QuoteTriggerHandler {
    public static void isBeforeInsert(List<Quote>QuoteList) {
        setNSLOnQuote(QuoteList); 
    }
    
    public static void setNSLOnQuote(List<Quote>QuoteList) {
        Set<Id>opportunityIds = new Set<Id>();
        for(Quote qt : QuoteList) {
            if(!String.isBlank(qt.opportunityId)) {
                opportunityIds.add(qt.opportunityId); 
                System.debug('opportunityIds=='+opportunityIds);
            }
        }
        Map<Id,Opportunity> opportunityMap = new Map<Id,Opportunity>([SELECT Name,NSL__c,CSL__c,CoCSL__c,RELBUL__c,RMP__c,Expertise__c,SubExpertise__c FROM Opportunity Where Id =:opportunityIds]);
        System.debug('opportunityMap==='+opportunityMap);
        
        for(Quote quote : QuoteList) {
            if(quote.NSL__c == null && quote.CSL__c == null && quote.CoCSL__c == null && quote.RELBUL__c == null && quote.RMP__c == null) {
                if(opportunityMap.containsKey(quote.OpportunityId)) {
                    quote.NSL__c = opportunityMap.get(quote.OpportunityId).NSL__c;
                    System.debug('quote.NSL__c==='+quote.NSL__c);
                    quote.CSL__c = opportunityMap.get(quote.OpportunityId).CSL__c;
                    System.debug('quote.CSL__c==='+quote.CSL__c);
                    quote.CoCSL__c = opportunityMap.get(quote.OpportunityId).CoCSL__c;
                    System.debug('quote.CoCSL__c==='+quote.CoCSL__c);
                    quote.RELBUL__c = opportunityMap.get(quote.OpportunityId).RELBUL__c;
                    System.debug('quote.RELBUL__c==='+quote.RELBUL__c);
                    quote.RMP__c = opportunityMap.get(quote.OpportunityId).RMP__c;
                    System.debug('quote.RMP__c==='+quote.RMP__c);
                }
            }
        }
        System.debug('QuoteList==='+QuoteList); 
    }
}