force-app/main/default/objects/Opportunity/fields/DueDateTillExpiry__c.field-meta.xml
<CustomField>
    <fullName>DueDateTillExpiry__c</fullName>
    <label>Due Date Till Expiry</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PendingDaysToExpire__c.field-meta.xml
<CustomField>
    <fullName>PendingDaysToExpire__c</fullName>
    <description>It will calculate pending days for RCC to expire.</description>
    <formula>DueDateTillExpiry__c  -  TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Remaining days till RCC expire.</inlineHelpText>
    <label>Pending Days To Expire</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RCCStatus__c.field-meta.xml
<CustomField>
    <fullName>RCCStatus__c</fullName>
    <label>RCC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Outstanding</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Not Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RCC__c/RCC__c.object-meta.xml
<CustomObject>
    <label>RCC</label>
    <nameField>
        <label>Name Of Entity</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RCCs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/RCC__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>RCCs</relationshipLabel>
    <relationshipName>RCCs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SendEmailToEOOnRCCExpire.cls
global class SendEmailToEOOnRCCExpire implements Database.Batchable<sObject>{
    // Start Method
    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id, Name, Owner.Email FROM Opportunity WHERE Id IN (SELECT Enquiry__c FROM RCC__c WHERE Enquiry__c != Null)';
        return Database.getQueryLocator(query);
    }
    // Execute Method
    global void execute(Database.BatchableContext BC, List<Opportunity> oppList){
        CustomNotificationType rccExpire = [SELECT Id FROM CustomNotificationType WHERE DeveloperName = 'RCC_Expire'];
        List<Opportunity> updatedOppList = new List<Opportunity>();
        List<Messaging.Email> emailList = new List<Messaging.Email>();
        if(!oppList.isEmpty()){
            for(Opportunity opp: oppList){
                if(opp.DueDateTillExpiry__c != Null && opp.PendingDaysToExpire__c != Null){
                    if(Date.Today() > opp.DueDateTillExpiry__c){
                        if(opp.StageName != 'Closed Won' || opp.StageName != 'Closed Lost'){
                            opp.RCCStatus__c = 'Expired';
                            updatedOppList.add(opp);
                            // Send Email To Enquiry Owner As Previous RCC Expired, Please Complete New RCC
                            Messaging.SingleEmailMessage emailMsg = new Messaging.SingleEmailMessage();
                            String[] toAddress = new String[]{opp.Owner.Email};
                            emailMsg.setToAddresses(toAddress);
                            emailMsg.setSubject('Please Complete RCC');
                            emailMsg.plaintextbody = 'Previous RCC Expired';
                            emailList.add(emailMsg);
                            
                            // Notification To Enquiry Owner As RCC Is About To Expire
                            Messaging.CustomNotification notification = new Messaging.CustomNotification();
                            notification.setBody('Previous RCC Expired, Please Complete RCC Again');
                            notification.setTitle(opp.Name);
                            notification.setTargetId(opp.Id);
                            notification.setNotificationTypeId(rccExpire.Id);
                            try {
                                notification.send(new Set<String> {opp.OwnerId});
                            }
                            catch (Exception e) {
                                System.debug('Problem sending notification: ' + e.getMessage());
                            }
                        }else if(opp.PendingDaysToExpire__c == 15 || opp.PendingDaysToExpire__c == 7){
                            Integer daysToExpire = 90 - Integer.valueOf(opp.PendingDaysToExpire__c);
                            // Send Email To Enquiry Owner As RCC is About To Expire
                            Messaging.SingleEmailMessage emailMsg = new Messaging.SingleEmailMessage();
                            String[] toAddress = new String[]{opp.Owner.Email};
                            emailMsg.setToAddresses(toAddress);
                            emailMsg.setSubject('Days Left Till RCC Expire');
                            emailMsg.plaintextbody = 'Only' + daysToExpire + 'Days Left Till RCC Expire';
                            emailList.add(emailMsg);
                            
                            // Notification To Enquiry Owner As RCC Is About To Expire
                            Messaging.CustomNotification notification = new Messaging.CustomNotification();
                            notification.setBody('Only' + daysToExpire + 'Days Left Till RCC Expire');
                            notification.setTitle(opp.Name);
                            notification.setTargetId(opp.Id);
                            notification.setNotificationTypeId(rccExpire.Id);
                            try {
                                notification.send(new Set<String> {opp.OwnerId});
                            }
                            catch (Exception e) {
                                System.debug('Problem sending notification: ' + e.getMessage());
                            }
                        }else{
                            
                        }
                    }
                }
            }
            try{
                Messaging.sendEmail(emailList);
            }catch(Exception e){
                System.debug('getmessage'+e.getMessage()+'getline number'+e.getLineNumber());
            }
            if(!updatedOppList.isEmpty()){
                update updatedOppList;
            }          
        }
    }
    
    // Finish Method
    global void finish(Database.BatchableContext BC){
        
    }
    
}