force-app/main/default/objects/Opportunity/fields/Executive_Assistant__c.field-meta.xml
<CustomField>
    <fullName>Executive_Assistant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Sharing to EA</description>
    <label>Executive Assistant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EnquiriesEA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NSL__c.field-meta.xml
<CustomField>
    <fullName>NSL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NSL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OpportunitiesnN4X</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EnquirySharingForEA.cls
public Without Sharing class EnquirySharingForEA {
    
    Public Static void EASharingRule(List<ID> enquiryIdList){
        List<Opportunity> EnquiryRecordList=[Select Executive_Assistant__c,Id from Opportunity where Id in:enquiryIdList]; 
        
        List<OpportunityShare>  opprtunitySharingList=new List<OpportunityShare>();
        For(opportunity opp:EnquiryRecordList){
            
            OpportunityShare OpportunitySharing=new OpportunityShare();
            system.debug('leadRecordList[0].Id'+opp.Id);  
            OpportunitySharing.OpportunityId=opp.Id;
            OpportunitySharing.OpportunityAccessLevel='Edit';
            system.debug('NSL'+opp.Executive_Assistant__c);  
            OpportunitySharing.UserOrGroupId=  opp.Executive_Assistant__c;
            OpportunitySharing.RowCause=Schema.OpportunityShare.RowCause.Manual;
            
            opprtunitySharingList.add(OpportunitySharing);
            
        }
        
        List<Database.SaveResult> sr = Database.insert(opprtunitySharingList,false); 
        
    }
    Public Static void NSLSharingRule(List<ID> enquiryIdList){
        List<Opportunity> EnquiryRecordList=[Select NSL__C,Id from Opportunity where Id in:enquiryIdList]; 
        
        List<OpportunityShare>  opprtunitySharingList=new List<OpportunityShare>();
        For(opportunity opp:EnquiryRecordList){
            
            OpportunityShare OpportunitySharing=new OpportunityShare();
            system.debug('leadRecordList[0].Id'+opp.Id);  
            OpportunitySharing.OpportunityId=opp.Id;
            OpportunitySharing.OpportunityAccessLevel='Edit';
            system.debug('NSL'+opp.NSL__C);  
            OpportunitySharing.UserOrGroupId=  opp.NSL__C;
            OpportunitySharing.RowCause=Schema.OpportunityShare.RowCause.Manual;
            
            opprtunitySharingList.add(OpportunitySharing);
            
        }
        
        List<Database.SaveResult> sr = Database.insert(opprtunitySharingList,false); 
        
    }
    
}