force-app/main/default/objects/Opportunity/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Recovery__c.field-meta.xml
<CustomField>
    <fullName>Recovery__c</fullName>
    <label>Recovery%</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/StagnatedEnquiriesController.cls
/*
 * Author : Suraj Kumar
 * Date : 27-12-2022
 * Description : Helper class of ReminderAccountPlanBatch
*/
public class StagnatedEnquiriesController {
    
    @AuraEnabled(Cacheable=True)
    public static List<Opportunity> getEnquiries(String Id){
        
        Opportunity opp = [SELECT Id, Name, StageName, Amount, Expertise__c, OwnerId, Recovery__c, CloseDate FROM Opportunity WHERE Id =: Id];
        Decimal lowerAmount = opp.Amount - (opp.Amount * 0.1);
        Decimal higherAmount = opp.Amount + (opp.Amount * 0.1);
        SYstem.debug('lowerAmount : ' + lowerAmount + ' and higherAmount : ' + higherAmount);
        List<Opportunity> oppList = [SELECT Id, Name, StageName, Amount, Expertise__c, Owner.Name, Recovery__c, CloseDate FROM Opportunity WHERE Amount >: lowerAmount AND Amount <: higherAmount AND StageName='Closed Won'];
        System.debug('oppList : ' + oppList);
        return oppList;
        
    }
}