force-app/main/default/objects/Creative_Hub__mdt/Creative_Hub__mdt.object-meta.xml
<CustomObject>
    <label>Creative Hub</label>
    <pluralLabel>Creative Hubs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Creative_Hub__mdt/fields/DocURL__c.field-meta.xml
<CustomField>
    <fullName>DocURL__c</fullName>
    <description>Url for document uplode</description>
    <label>DocURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Creative_Hub__mdt/fields/Grant_Type__c.field-meta.xml
<CustomField>
    <fullName>Grant_Type__c</fullName>
    <label>Grant_Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Creative_Hub__mdt/fields/Token_End_Point_URL__c.field-meta.xml
<CustomField>
    <fullName>Token_End_Point_URL__c</fullName>
    <label>Token End Point URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Creative_Hub__mdt/fields/urlForDocBinding__c.field-meta.xml
<CustomField>
    <fullName>urlForDocBinding__c</fullName>
    <label>urlForDocBinding</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/IntegratedEnquiry__c.object-meta.xml
<CustomObject>
    <label>Integrated Enquiry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integrated Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Child_Enquiries__c.field-meta.xml
<CustomField>
    <fullName>Child_Enquiries__c</fullName>
    <label>Child Enquiries</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/ClientName__c.field-meta.xml
<CustomField>
    <fullName>ClientName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Integrated Enquiries (Client Name)</relationshipLabel>
    <relationshipName>Integrated_Enquiries3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Creative_Hub_Id__c.field-meta.xml
<CustomField>
    <fullName>Creative_Hub_Id__c</fullName>
    <label>Creative Hub Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Creative_Hub_Status__c.field-meta.xml
<CustomField>
    <fullName>Creative_Hub_Status__c</fullName>
    <label>Creative Hub Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Expertise__c.field-meta.xml
<CustomField>
    <fullName>Expertise__c</fullName>
    <label>Expertise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Solution1__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Expertise</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Job_Code__c.field-meta.xml
<CustomField>
    <fullName>Job_Code__c</fullName>
    <label>Job Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Lead_member_firm__c.field-meta.xml
<CustomField>
    <fullName>Lead_member_firm__c</fullName>
    <label>Lead member firm</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Antigua and St Kitts &amp; Nevis</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>British Virgin Islands</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Cameroon</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Cayman Islands</fullName>
            </value>
            <value>
                <fullName>Channel Islands</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>China &amp; Hong Kong</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Côte d’Ivoire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Legal_entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_entity__c</fullName>
    <label>Legal entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Grant Thornton Advisory Private Limited</fullName>
            </value>
            <value>
                <fullName>Grant Thornton Bharat LLP</fullName>
            </value>
            <value>
                <fullName>GT Restructuring Services LLP</fullName>
            </value>
            <value>
                <fullName>GT Valuation Advisors LLP</fullName>
            </value>
            <value>
                <fullName>Walker Chandiok &amp; Associates</fullName>
            </value>
            <value>
                <fullName>Walker Chandiok &amp; Co LLP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Level_of_support__c.field-meta.xml
<CustomField>
    <fullName>Level_of_support__c</fullName>
    <label>Level of support</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Branding View</fullName>
            </value>
            <value>
                <fullName>Content View</fullName>
            </value>
            <value>
                <fullName>Build document</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Pitch_Presentation_Status__c.field-meta.xml
<CustomField>
    <fullName>Pitch_Presentation_Status__c</fullName>
    <label>Pitch Presentation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Creative_Hub_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Proposal_Status__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Status__c</fullName>
    <label>Proposal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Creative_Hub_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Proposal_value__c.field-meta.xml
<CustomField>
    <fullName>Proposal_value__c</fullName>
    <label>Proposal value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Reason_for_request__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_request__c</fullName>
    <label>Reason for request</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client Meeting</fullName>
            </value>
            <value>
                <fullName>Need to sent to client</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pitch Presentation</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Specify_details_of_content__c.field-meta.xml
<CustomField>
    <fullName>Specify_details_of_content__c</fullName>
    <label>Specify details of content</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Support_required__c.field-meta.xml
<CustomField>
    <fullName>Support_required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Support required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Type_of_content__c.field-meta.xml
<CustomField>
    <fullName>Type_of_content__c</fullName>
    <label>Type of content</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case studies &amp; testimonials</fullName>
            </value>
            <value>
                <fullName>Credentials</fullName>
            </value>
            <value>
                <fullName>CV</fullName>
            </value>
            <value>
                <fullName>Member Firm Information</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Sector Insights</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegratedEnquiry__c/fields/Type_of_document__c.field-meta.xml
<CustomField>
    <fullName>Type_of_document__c</fullName>
    <label>Type of document</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pitch Presentation</fullName>
            </value>
            <value>
                <fullName>Placemat</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Creative_Hub_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>InProgress</fullName>
    </customValue>
    <customValue>
        <fullName>Pipeline</fullName>
    </customValue>
    <customValue>
        <fullName>Delete</fullName>
    </customValue>
    <description>Value set for creative hub status (Proposal &amp; pitchdeck status on integrated Enquiry and  Enquiry)</description>
    <masterLabel>Creative Hub Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Auto &amp; Auto Components</fullName>
    </customValue>
    <customValue>
        <fullName>CIP &amp; Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Services</fullName>
    </customValue>
    <customValue>
        <fullName>Global Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Law Firms</fullName>
    </customValue>
    <customValue>
        <fullName>Owners &amp; Private Clients</fullName>
    </customValue>
    <customValue>
        <fullName>PE/VC</fullName>
    </customValue>
    <customValue>
        <fullName>Pharma &amp; Healthcare Services</fullName>
    </customValue>
    <customValue>
        <fullName>Real Estate &amp; Infra</fullName>
    </customValue>
    <customValue>
        <fullName>TMT</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <description>This is having all the sector details of GT.</description>
    <masterLabel>Sector</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreativeHubAPIController.cls
public class CreativeHubAPIController {
    @InvocableMethod
    public static void invocable(List<Id> oppoIds){
        sendRequest(oppoIds);
    }
    @future(callout=true)
    public static void sendRequest(List<Id> oppoIds){
        String UserEmail = UserInfo.getUserEmail();
        
        List<IntegratedEnquiry__c > oppoList=[select Id, Type_of_content__c, Specify_details_of_content__c, Reason_for_request__c, Job_Code__c,
                                              Type_of_document__c, Level_of_support__c,ClientName__c, Legal_Entity__c, Lead_member_firm__c,
                                              Proposal_value__c,Support_required__c,CreatedBy.Name,Child_Enquiries__c,Attachment__C,
                                              (Select ContentDocumentId,contentdocument.title, ContentDocument.LatestPublishedVersionId  from contentdocumentlinks order by ContentDocument.LatestPublishedVersionId desc limit 1)content,
                                              
                                              Sector__c, Expertise__c from IntegratedEnquiry__c  where Id In:oppoIds];
        System.debug('oppoList====>'+oppoList);
        
        
        Creative_Hub__mdt apiMetaData = [select id,Client_id__c,Client_Secret__c,urlForDocBinding__C,End_Point_URL__c,Grant_Type__c,Scope__c,
                                         Token_End_Point_URL__c,DocURL__c from Creative_Hub__mdt where MasterLabel='Creative Hub Meta Data' limit 1];
        String requestBody ='client_id='+apiMetaData.Client_id__c+'&client_secret='+apiMetaData.Client_Secret__c
            +'&scope='+apiMetaData.Scope__c+'&grant_type='+apiMetaData.Grant_Type__c;
        
        HttpRequest postRequest = HttpUtility.getHttpRequest(apiMetaData.Token_End_Point_URL__c,'POST',null,null,requestBody,'application/x-www-form-urlencoded', null);
        HttpResponse postResponse = HttpUtility.makeCallout(postRequest);
        system.debug('Response Token'+postResponse.getBody());
        AccessTokenGenerator accessToken = (AccessTokenGenerator) JSON.deserialize(postResponse.getBody(),AccessTokenGenerator.class);
        
        String body = '{ "fields": { ' +
            '"UserEmail":"'+UserEmail+'",'+
            '"TypeOfDocument":"'+oppoList[0].Type_of_document__c+'",'+
            '"LevelOfSupport":"'+oppoList[0].Level_of_support__c+'",'+
            '"ClientName":"'+oppoList[0].ClientName__c+'",'+
            '"Sector":"'+oppoList[0].Sector__c+'",'+
            '"SubSector":"'+oppoList[0].Sector__c+'",'+
            '"DetailsOfSupport":"'+oppoList[0].Type_of_document__c+'",'+
            '"LegalEntity":"'+oppoList[0].Legal_Entity__c+'",'+
            '"LeadMemberFirm":"'+oppoList[0].Lead_member_firm__c+'",'+
            '"PipeLineID":"'+oppoList[0].Id+'",'+
            '"ProposalValue":"'+oppoList[0].Proposal_value__c+'",'+
            '"SupportRequired":"'+oppoList[0].Support_required__c+'",'+
            '"TypeOfContent":"'+oppoList[0].Type_of_content__c+'",'+
            '"DetailsOfContent":"'+oppoList[0].Specify_details_of_content__c+'",'+
            '"ReasonForRequest":"'+oppoList[0].Reason_for_request__c+'",'+
            '"TypeOfBranding":"'+oppoList[0].Type_of_document__c+'",'+
            '"RaiseBy":"LinKreta",'+
            '"RequestorName":"'+oppoList[0].CreatedBy.Name+'",'+
            '"JobCode":"13-11-GTBL001-002-NCA-NR-2021-00001",'+
            '"ChildPipelineIds":"'+oppoList[0].Child_Enquiries__c+'"'+
            '        }' +
            '}';
        String bearerAccessToken='Bearer '+accessToken.access_token;
        
        HttpRequest apiRequest = HttpUtility.getHttpRequest(apiMetaData.End_Point_URL__c,'POST','accept','*/*',body,'application/json', null);
        apiRequest.setHeader('Authorization', bearerAccessToken);
        HttpResponse apiResponse = HttpUtility.makeCallout(apiRequest);
        System.debug('Status code'+apiResponse.getStatusCode());
        System.debug('APi Response'+apiResponse.getBody());
        CreativeHubAPIController.wrapperClass wrapObj = (CreativeHubAPIController.wrapperClass)JSON.deserialize(apiResponse.getBody(), CreativeHubAPIController.wrapperClass.class);
        System.debug('wrapObj :'+wrapObj);
        
        
        if(wrapObj != null && apiResponse.getStatusCode()==201 && oppoList[0].Attachment__C==true){
            ContentVersion cntv =[SELECT Id,Title,ContentDocumentId,versiondata,IsLatest FROM ContentVersion WHERE IsLatest=true and ContentDocumentId =:oppoList[0].ContentDocumentLinks[0].ContentDocumentId LIMIT 1]; 
            system.debug('Title'+cntv.Title);
            string str='';
            str+=Datetime.now();
            
            string str2=str.replace(' ','');
            String str3=str2.replace('-','');
            String str4=str3.replace(':','');
            system.debug('str'+str);
            String url=apiMetaData.DocURL__c+cntv.Title+str4;
            String url1=url+'.pdf:/content';
            String url2=url+'.pdf:/listItem/fields';
            system.debug('url'+url);
            
            string contentData =EncodingUtil.base64Encode(cntv.VersionData);
            system.debug('bearerAccessToken'+bearerAccessToken);
            HttpRequest apiRequestdoc = HttpUtility.getHttpRequest(url1,'PUT','accept','*/*',contentData,'application/json', null);
            apiRequestdoc.setHeader('Authorization', bearerAccessToken);
            HttpResponse apiResponsedoc = HttpUtility.makeCallout(apiRequestdoc);
            System.debug('Status code'+apiResponsedoc.getStatusCode());
            System.debug('APi Response'+apiResponsedoc.getBody());
           
             if(apiResponsedoc.getStatusCode()==200){
            String bodyrequestId='{ ' +
                '"RequestID":"'+wrapObj.id+'"}';
                
            HttpRequest apiRequestdocAttached = HttpUtility.getHttpRequest(url2,'PATCH','accept','*/*',bodyrequestId,'application/json', null);
            apiRequestdocAttached.setHeader('Authorization', bearerAccessToken);
            HttpResponse apiResponsedocAttached = HttpUtility.makeCallout(apiRequestdocAttached);
            System.debug('Status code'+apiResponsedocAttached.getStatusCode());
            System.debug('APi Response'+apiResponsedocAttached.getBody());
             updateCreativeIdAndStatus(wrapObj);
             }}
    
       
        
    }
    public static void updateCreativeIdAndStatus(wrapperClass obj){
        IntegratedEnquiry__c intGraObj = [SELECT Id,Creative_Hub_Id__c,Type_of_document__C,Proposal_Status__c,Pitch_Presentation_Status__C,Creative_Hub_Status__c FROM IntegratedEnquiry__c WHERE Id =: obj.fields.PipeLineID];
        if(intGraObj.Type_of_document__C=='Pitch Presentation'){
           
           intGraObj.Pitch_Presentation_Status__C=obj.fields.RequestStatus;
        }else{
             intGraObj.Proposal_Status__c=obj.fields.RequestStatus;
        }
        intGraObj.Creative_Hub_Id__c = obj.Id;
        intGraObj.Creative_Hub_Status__c = obj.fields.RequestStatus;
        intGraObj.Attachment__C=false;
        update intGraObj;
    }
      

    @future(callout=true)
    public static void uploadeDocumentToCreativeHub(id contentVersionId){
        
        ContentVersion cntv =[SELECT Id,Title,ContentDocumentId,versiondata,IsLatest FROM ContentVersion WHERE IsLatest=true and ContentDocumentId =:contentVersionId LIMIT 1]; 
        string contentData =EncodingUtil.base64Encode(cntv.VersionData);
        system.debug('cntv'+contentData);
        
        Creative_Hub__mdt apiMetaData = [select id,Client_id__c,Client_Secret__c,End_Point_URL__c,Grant_Type__c,Scope__c,
                                         Token_End_Point_URL__c,DocURL__c from Creative_Hub__mdt where MasterLabel='Creative Hub Meta Data' limit 1];
        String requestBody ='client_id='+apiMetaData.Client_id__c+'&client_secret='+apiMetaData.Client_Secret__c
            +'&scope='+apiMetaData.Scope__c+'&grant_type='+apiMetaData.Grant_Type__c;
        HttpRequest apiRequest = HttpUtility.getHttpRequest(apiMetaData.DocURL__c,'PUT','accept','*/*',contentData,'application/json', null);
        HttpRequest postRequest = HttpUtility.getHttpRequest(apiMetaData.Token_End_Point_URL__c,'POST',null,null,requestBody,'application/x-www-form-urlencoded', null);
        HttpResponse postResponse = HttpUtility.makeCallout(postRequest);
        system.debug('Response Token'+postResponse.getBody());
        AccessTokenGenerator accessToken = (AccessTokenGenerator) JSON.deserialize(postResponse.getBody(),AccessTokenGenerator.class);
         String bearerAccessToken='Bearer '+accessToken.access_token;
        apiRequest.setHeader('Authorization', bearerAccessToken);
        HttpResponse apiResponse = HttpUtility.makeCallout(apiRequest);
        System.debug('Status code'+apiResponse.getStatusCode());
        System.debug('APi Response'+apiResponse.getBody());
        
        
        
        
    }
    public class AccessTokenGenerator{
        public String token_type;	
        public Integer expires_in;
        public Integer ext_expires_in;	
        public String access_token;
    }
    public class wrapperClass{
        public string id;
        public Fields fields;
    }
    public class Fields{
        public string id;
        public string RequestStatus;
        public string ReasonForRequest;
        public string TypeOfBranding;
        public string LevelOfSupport;
        public string PipeLineID;
        public string ClientName;
        public string DetailsOfSupport;
        public string Sector;
        public string SubSector;
        
    }
}