force-app/main/default/objects/Solution_Mapping_With_Expertice__mdt/Solution_Mapping_With_Expertice__mdt.object-meta.xml
<CustomObject>
    <description>Solution Mapping With Expertice custom LWC Page</description>
    <label>Solution Mapping With Expertice</label>
    <pluralLabel>Solution Mapping With Expertices</pluralLabel>
</CustomObject>

force-app/main/default/objects/Solution_Mapping_With_Expertice__mdt/fields/Expertice__c.field-meta.xml
<CustomField>
    <fullName>Expertice__c</fullName>
    <description>Semicolumn Seprated expertice</description>
    <label>Expertice</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/dependancySolutionWithExperties.cls
public with sharing class dependancySolutionWithExperties {
    @AuraEnabled(cacheable=true)
       public static List<PiclistWrapperClass> PicklistValues(String Solution){
         List<PiclistWrapperClass> wrapperList = new List<PiclistWrapperClass>();
         Solution_Mapping_With_Expertice__mdt SolutionExperties = [select Label, Expertice__c from Solution_Mapping_With_Expertice__mdt where Label=:Solution];
         List<String> ListOfExperties = new List<String>();
         ListOfExperties= SolutionExperties.Expertice__c.split(';');
           for(String res : ListOfExperties) {
                
                  PiclistWrapperClass pwc = new PiclistWrapperClass();
                   pwc.picklistvalue = res;
                   pwc.picklistlabel=  res;
                     wrapperList.add(pwc);
                 }
              
           
           return wrapperList;
        }
   
        public class PiclistWrapperClass{
           @AuraEnabled public String picklistvalue;
           @AuraEnabled public String picklistlabel;
        }
   }